### ISSUE TITLE
Login using a github-only account that is not linked to OpenShift fails - does not return error message to user

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-ui#1009]
Steps to recreate:

* With a github only account
* Login to https://prod-preview/openshift.io
* Observe that a 400 (bad request) error is logged, that the user's URL is set to https://prod-preview/openshift.io/_gettingstarted, and a blank browser window is displayed to the user

Workaround:
* Delete _gettingstarted from the URL
* Force a reload of the browser

NOTE - This bug blocks automated  EE testing.

**Comment by hectorj2f** [comment]
A video about the issue can be found here: https://cloud.githubusercontent.com/assets/3602792/25344987/09a37d3c-2914-11e7-8931-afff1c9f647d.gif

**Comment by hectorj2f** [comment]
In keycloak, I found this error which is logical cause this user isn't associated to openshift-v3 
```
 User [54ec4657-7802-4abf-b03c-b3e1b76999ae] is not associated with identity provider [openshift-v3].
```

**Comment by alexeykazakov** [comment]
That 400 is expected if there is no OSO link. The problem is in UI which should ask user to link OSO if it's not linked yet.

**Comment by ldimaggi** [comment]
So - the sequence for a new user - a user who only has a github account - is (1) connect his github account to openshift (https://sso.prod-preview.openshift.io/auth/realms/fabric8/account/identity) , and then (2) login to prod-preview.openshift.io, yes?     

The login is successful, but it then hits this bug - https://github.com/fabric8io/fabric8-ui/issues/994

The problem in https://github.com/fabric8io/fabric8-ui/issues/994 is that UI doesn't properly handle unlink accounts. If OSO is not linked then it should ask user to link

**Comment by joshuawilson** [comment]
@ldimaggi please verify.

**Comment by ldimaggi** [comment]
No longer a bug - closing.
