### ISSUE TITLE
URL for stack service needs to be passed as an environment variable.

### ISSUE THREAD

**Issue by sbose78** [fabric8io/fabric8-ui#101]

**Comment by sbose78** [comment]
Related task on the deployment side is tracked here:
https://github.com/almighty/almighty-jobs/issues/72

**Comment by invincibleJai** [comment]
this has been taken care as PR #119 

https://github.com/fabric8io/fabric8-ui/blob/master/src/app/analyze/stack/stack-analyses.service.ts

can it be closed?
