### ISSUE TITLE
UI should list somewhere the openshift console and/or api urls

### ISSUE THREAD

**Issue by maxandersen** [fabric8io/fabric8-ui#1017]
Once you run the wizards you don't have a way to actually browse to see the openshift console nor info on what api urls to use if using `oc`

Suggestion is to have the environment "tile" actually give a link to your spaces openshift console project(s)/environments - or at least a minimum the main console.

This would at least allow users to browse the details and find info to get cli access.

p.s. The environment page currently seems hardcoded to point to https://console.free-int.openshift.com/ instead of https://console.starter-us-east-2.openshift.com/console/ - which is just wrong for openshift.io.

**Comment by maxandersen** [comment]
from @pmuir on this from mailing list:
There will be links from the environments widget, and we will add the
applications page (like the environments page but better) after
Summit.

We're also adding the access tokens to the profile again, and it could
be good to have link to the openshift console there as well.

**Comment by jstrachan** [comment]
this PR adds a link to the openshift console on the Pipelines page

**Comment by sbose78** [comment]
This has been fixed here https://github.com/fabric8io/fabric8-ui/pull/1062/files#diff-28519934ef78f3a7270b64304cb53b39R178
