### ISSUE TITLE
Able to create a space without any specified template 

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-ui#1027]
Able to create a space without any specified template 
Steps to reproduce
- create a space 
- don't choose any template 

expected result : there should be some default space template incase user is not selecting one.  

video link : https://drive.google.com/a/redhat.com/file/d/0B1qUq_laG6CObEVhMS03aDhDMms/view?usp=sharing

**Comment by joshuawilson** [comment]
duplicates #390

**Comment by joshuawilson** [comment]
Closing as it is a duplicate.
