### ISSUE TITLE
Multiple encoding in `namedspaces` requests

### ISSUE THREAD

**Issue by xcoulon** [fabric8io/fabric8-ui#1036]
I'm getting some errors in the backend console such as this one, along with problems in the UI when trying to update a work item:

````
12:2:52 app         | time="2017-04-25 12:02:52" level=error msg="Fail to locate Keycloak identity for user" file="/Users/xcoulon/code/go/src/github.com/almighty/almighty-core/controller/namedspaces.go" func="github.com/almighty/almighty-core/controller.loadKeyCloakIdentityByUserName" line=105 pid=41549 pkg=controller req_id=d2c73e7d-ba71-4b91-a347-457e58f196f7 username="xcoulon%!r(MISSING)edhat.com"
````

I have an identity with `username=xcoulon@redhat.com` in my DB, but I suspect that there's an encoding problem with the `@` character somewhere. 

Looking in the browser console, I found the following request:
````
GET http://localhost:8080/api/namedspaces/xcoulon%2540redhat.com/testing5
````

There seems to be a double-encoding which causes the URL to be invalid:
1) when `xcoulon@redhat.com` is encoded on the first call, it becomes `xcoulon%40redhat.com` (`@` became `%40`)
2) on the second call, `xcoulon%40redhat.com` is encoded again, giving `xcoulon%2540redhat.com` this time. Ie, that's the `%` character that is encoded into `%25`. As a result, the `GET http://localhost:8080/api/namedspaces/xcoulon%2540redhat.com/testing5` is invalid and the server returns a `404 Not Found` response.

Steps to reproduce: 
- login to fabric8 UI
- create a new space
- add a work item (not using the quick editor)
- upon saving the WI title and closing the side dialog, a toaster displays the following error message: `/xcoulon%252540redhat.com/testing8/plan not found`

**Comment by joshuawilson** [comment]
@xcoulon I think this is fixed. I'm going to close it. If you are still having an issue please reopen it.
