### ISSUE TITLE
Pipelines toolbar issues

### ISSUE THREAD

**Issue by dlabrecq** [fabric8io/fabric8-ui#1069]
The toolbar for pipelines does not stretch the full width of the page and also covers the secondary navigation bar.

The toolbar probably shouldn't be wrapped in class="content container". Look at the codebases toolbar implementation, which doesn't use that.

Also need UXD to look at how the OpenShift link is added in the toolbar's view area. This is really not intended to show links or buttons.

Please see comments from #1062 and 1032

**Comment by catrobson** [comment]
@dlabrecq do you have a screenshot of the OpenShift link in the toolbar?  Not familiar with what you're seeing.  Otherwise I think @mindreeper2420 was already looking at how to fix the container on his list, but if you can fix this it would take one thing off of his list!

**Comment by dlabrecq** [comment]
<img width="1437" alt="screen shot 2017-04-26 at 10 12 37 pm" src="https://cloud.githubusercontent.com/assets/17481322/25464990/8a1211bc-2acd-11e7-8d24-d41759cdcfec.png">

**Comment by catrobson** [comment]
+1 that the link should not be there.  Each Deployment-Config (Demo in this case) should link to the OpenShift console instead.
