### ISSUE TITLE
Question: Should spaces be created in the first stage of the create space dialog?

### ISSUE THREAD

**Issue by VineetReynolds** [fabric8io/fabric8-ui#107]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[x] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

Requesting clarity on whether spaces should be created in the first stage of the spaces wizard, or whether the dialog needs to be improved to convey that a new space will be created in the first stage.

* **What is the current behavior?**

The first dialog in the wizard has a *Next* button, which does not imply that the space will be immediately created.

<img width="602" alt="createspacewizard-1" src="https://cloud.githubusercontent.com/assets/792234/22688515/a3a418ae-ed52-11e6-9c2e-21b43d40d581.png">

The second dialog however displays that the space has been created. This is confusing to the user, given the presence of a *Back* button in the dialog.

<img width="599" alt="createspacewizard-2" src="https://cloud.githubusercontent.com/assets/792234/22688647/34bac7ac-ed53-11e6-9c3a-08029f7f447c.png">

* **What is the motivation / use case for changing the behavior?**

If spaces are to be created in the first dialog of the wizard, then the dialog should not allow for multiple spaces to be created by the user accidentally.

**Comment by mitchharpur** [comment]
This is just because it was in the mockup and will probably change as the wizard evolves with the obsidian api over the next several weeks. The space is created on the finish button

**Comment by joshuawilson** [comment]
@aslakknutsen do know you the answer to the above question?

**Comment by pmuir** [comment]
As @mitchharpur said, right now we just copied the mockup from @qodfathr but the mockup contains a logical flaw - the screen allows you to go back, but it also says that part of the transaction is complete (creating the space). @qodfathr can you tell us how you want the mockup altered to resolve?

**Comment by pmuir** [comment]
@Essjaysee is working on this

**Comment by aslakknutsen** [comment]
Personally, I wouldn't see it is one large popup wizard. In my mind the 'get started' makes more sense as the default 'dashboard' landing page for an empty space. 'get started' is also something you would want to do over and over again inside the same space which means you need to know where to get access to that part of the wizard anyway.

**Comment by pmuir** [comment]
This specific question is now addressed, there is a create space button.
