### ISSUE TITLE
Rename Start Collaborating to ...

### ISSUE THREAD

**Issue by pmuir** [fabric8io/fabric8-ui#111]
On http://console.prod-preview.openshift.io/home rename the button.

@qodfathr please provide the new name

Please then assign to me to make code fix, or send PR :-)

**Comment by pmuir** [comment]
@muruGanesan is working onthe designs for this

**Comment by muruGanesan** [comment]
@pmuir, Jessica worked on the screen. You can see the (wireframe) mock up  here: https://redhat.invisionapp.com/share/XZAOBAOPB#/screens

**Comment by pmuir** [comment]
@muruGanesan is this ready for us to start implementing? If so, can @SMahil do an initial html/css pass through for us? /cc @maxandersen @michaelkleinhenz

**Comment by joshuawilson** [comment]
I think we should expand the scope of the issue to "implement the homescreen design". 

@SMahil are you able to take this on?

**Comment by SMahil** [comment]
Sure @joshuawilson

**Comment by joshuawilson** [comment]
thanks @SMahil

**Comment by joshuawilson** [comment]
This appears fixed, closing.
