### ISSUE TITLE
Menu bar is not loading if you don't enter a username in to the signup screen

### ISSUE THREAD

**Issue by pmuir** [fabric8io/fabric8-ui#112]
I made an async error when I rewired the context service, and I managed to allow the menu bar to disappear if someone somehow doesn't have a username set up

**Comment by pmuir** [comment]
Requires username to be returned in request to /api/user

**Comment by alexeykazakov** [comment]
Related to https://github.com/almighty/almighty-core/issues/735

**Comment by alexeykazakov** [comment]
Username will be returned by /api/user when the following PR is merged https://github.com/almighty/almighty-core/pull/692

**Comment by alexeykazakov** [comment]
almighty/almighty-core#692 has been merged - username is now available in JSON returned by /api/user

**Comment by alexeykazakov** [comment]
Details: http://swagger.goa.design/?url=github.com%2Falmighty%2Falmighty-core%2Fdesign#!/user/user_show
