### ISSUE TITLE
Stack report on space dashboard - Redesign needed

### ISSUE THREAD

**Issue by catrobson** [fabric8io/fabric8-ui#1124]
For summit, we would like to change the stack report on the space dashboard to work differently than it does today.  Specs included below.  Filled state changes are a priority for summit demo.

![stackanalysiswidget_newdesignforsummit](https://cloud.githubusercontent.com/assets/3739227/25460739/1b35af20-2ab3-11e7-8545-4270a746a40c.jpg)

Changes include:
- Change the title to “Stack Report Recommendations”
- Remove "Recommendations" title in the widget
- Move Pipeline selection to right side of header.  Build selection should be dropped.  We will default to the latest build that has a stack report to show.  For more builds they will have to go to the pipeline history.
- 7 recommendations should fit into the widget, we will show only the top 7 recommendations.
- The user can get to the full report from the link at the bottom of this widget.  The title should not change to a link.  This should always be aligned to the bottom of the widget, even if there is only 1 or 2 recommendations to show.
- The date/timestamp of the report completion should be shown in the bottom right of the widget.
This should always be at the bottom right of the widget, aligned at the same vertical spot as
the full report link.

A new empty state has also been included, but is not a priority for summit.

**Comment by arunkumars08** [comment]
@catrobson How will the scenario be in case we have pipelines and no builds related to Bayesian (Meaning, we don't have any information from Bayesian)

**Comment by joshuawilson** [comment]
It will be empty, for now use the current empty state text you have.

The list in the drop down should only have pipelines that have builds that have Stack reports for them. You should not show all possible pipelines or builds.

**Comment by joshuawilson** [comment]
Note what is the 2nd point, "default to the latest build that has a stack report".

**Comment by joshuawilson** [comment]
@catrobson do the stack reports match the design or is there still more work on this issue? If it is done, please close the issue.

**Comment by catrobson** [comment]
I'm unable to get a stack report running to verify.  Can someone screenshot the latest?

**Comment by joshuawilson** [comment]
Here is what I have.
![osio-stack-dashboard](https://user-images.githubusercontent.com/1184371/27364592-7157056c-5609-11e7-8321-f412a285f0af.png)
![osio-stack-report](https://user-images.githubusercontent.com/1184371/27364593-7159fa42-5609-11e7-92f7-cdd889651c07.png)

**Comment by catrobson** [comment]
Thanks @joshuawilson.  Closing.
