### ISSUE TITLE
Deleted spaces are not refreshed in/removed from the displayed list of recent spaces until a user logs out

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-ui#1156]
Screenshot #1 - After the space is created

![screenshot from 2017-04-27 11-00-13](https://cloud.githubusercontent.com/assets/642621/25490219/239f6eb2-2b3a-11e7-84a3-2fc51e336a87.png)

Screenshot #2 - After the space is deleted

![screenshot from 2017-04-27 11-01-00](https://cloud.githubusercontent.com/assets/642621/25490233/2f5a51b8-2b3a-11e7-9d68-f8d9f59d98dc.png)

**Comment by joshuawilson** [comment]
This has been fixed.
