### ISSUE TITLE
On login, a user's spaces are not listed in the home page

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-ui#1157]
Screenshot #1 - On login, no spaces are displayed:

![screenshot from 2017-04-27 11-17-20](https://cloud.githubusercontent.com/assets/642621/25490679/8b7869e8-2b3b-11e7-9075-e944b40d8921.png)

Screenshot #2 - But, the user does have spaces:

![screenshot from 2017-04-27 11-17-41](https://cloud.githubusercontent.com/assets/642621/25490701/99b2046a-2b3b-11e7-96d2-8b92e49743c6.png)

**Comment by joshuawilson** [comment]
it is only recent spaces
