### ISSUE TITLE
Multiple UI elements are assigned the same name/ID on the same UI page

### ISSUE THREAD

**Issue by almightytest** [fabric8io/fabric8-ui#118]
Multiple UI elements are assigned the same name/ID on the same UI page - this makes test automation more difficult. See attached screenshots - can we assign a unique ID to each UI element, within the context of a UI page:

![projectname_2](https://cloud.githubusercontent.com/assets/23330096/22844427/39630b42-efac-11e6-8da6-4dda225247ac.png)
![projectname_1](https://cloud.githubusercontent.com/assets/23330096/22844428/396b836c-efac-11e6-9d9a-072d28ee1cb4.png)

**Comment by mitchharpur** [comment]
this code is no longer part of the solution
