### ISSUE TITLE
Remove images from project type dropdown in wizard

### ISSUE THREAD

**Issue by catrobson** [fabric8io/fabric8-ui#1180]
The images next to the project types (vert.x, swarm, etc) are poor quality, stretched, and don't have transparency.  We should remove these for now and go back to just a text list selection as previously implemented for this dropdown.

**Comment by joshuawilson** [comment]
@mitchharpur If you can get this done, I'll like to get it merged. Thanks

**Comment by mitchharpur** [comment]
done
