### ISSUE TITLE
Intermittent problem - Clicking on in planner causes the quick add bar to disappear

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-ui#1182]
Seeing this occur - not every time - clicking on the quick add option causes it to disappear. No error is logged in the console log:

![screenshot from 2017-04-27 17-16-54](https://cloud.githubusercontent.com/assets/642621/25504943/cde0002a-2b6d-11e7-8a85-adcf773a6e72.png)

**Comment by ldimaggi** [comment]
Leaving and returning to the planner restores the quick add bar.

**Comment by michaelkleinhenz** [comment]
@ldimaggi again, can not verify over here. You did click on the "Create Work Item" label on the closed quick add to trigger this, correct?

**Comment by ldimaggi** [comment]
Yes - but - this is a diff problem - as is shown in the screenshot - the quick add simply disappeared.

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-planner#2019
