### ISSUE TITLE
Iteraton dates - the dates selected are saved as (date - 1) - ONLY in USA timezones

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-ui#1188]
Here is an iteration as created:

![screenshot from 2017-04-27 17-38-49](https://cloud.githubusercontent.com/assets/642621/25505603/89140a10-2b70-11e7-9b23-3708ba698917.png)

And - here is how it is save by the Planner::

![screenshot from 2017-04-27 17-39-14](https://cloud.githubusercontent.com/assets/642621/25505616/9b9838fa-2b70-11e7-8095-9b76b249361e.png)

**Comment by michaelkleinhenz** [comment]
@ldimaggi I also can not reproduce this behaviour. I created several iterations, setting dates on creation or later and dates are consistent. Could that be a timezone problem? Can you look at the raw API output of your failing case? That would be "https://api.prod-preview.openshift.io/api/spaces/SPACEID/iterations" with SPACEID your space id.

**Comment by ldimaggi** [comment]
This may be related to timezones.

This is failing in the EDT/USA (East Coast) timezone - it's not failing for Michael.

**Comment by michaelkleinhenz** [comment]
Ok, confirmed this is only happening in US timezones. Looking at it now.

**Comment by michaelkleinhenz** [comment]
Fixed in https://github.com/fabric8io/fabric8-planner/pull/1824
