### ISSUE TITLE
UI div overflow in create new space modal screen

### ISSUE THREAD

**Issue by samuzzal-choudhury** [fabric8io/fabric8-ui#1201]
Test System: Mac Pro 15.4-inch (2880 x 1800)

While creating a new space on my system, I observed overflow in "Select build pipeline strategy ..." and "Application Generator Results" screens. Please checkout of the attached screens for ready reference.

![image](https://cloud.githubusercontent.com/assets/17740190/25517487/4b09e7c4-2c0d-11e7-91b8-7dbd20a8af04.png)

![image](https://cloud.githubusercontent.com/assets/17740190/25517502/58fcfbf0-2c0d-11e7-8ede-feae4905cb56.png)

**Comment by joshuawilson** [comment]
What browser and OS are you using?

**Comment by arunkumars08** [comment]
This happens when we try to create a new space from the 'View all spaces' screen. Tested in Chrome @joshuawilson @samuzzal-choudhury

**Comment by joshuawilson** [comment]
@mindreeper2420 can you please look into this.

**Comment by joshuawilson** [comment]
related to #1517

**Comment by mindreeper2420** [comment]
@joshuawilson This should be fixed as part of PR #1419.
