### ISSUE TITLE
Screen display is corrupted when creating new space project in Firefox on Windows

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-ui#1208]
Firefox screenshot:

![screenshot 2](https://cloud.githubusercontent.com/assets/642621/25535709/10c559ce-2c06-11e7-9ef9-16904a4359b1.png)

In contrast - here's the same operation in Chrome:

![screenshot 3](https://cloud.githubusercontent.com/assets/642621/25535731/2137835e-2c06-11e7-880e-453896bf4b3a.png)

**Comment by ldimaggi** [comment]
This is on Windows 10

**Comment by mindreeper2420** [comment]
@joshuawilson @ldimaggi I was not able to replicate this on Firefox for Mac, but I did find another issue using:
<img width="1920" alt="screen shot 2017-04-28 at 9 37 42 pm" src="https://cloud.githubusercontent.com/assets/4032718/25551922/206e4eda-2c5b-11e7-8b12-4a7fc29d7dd6.png">

**Comment by mindreeper2420** [comment]
@ldimaggi @joshuawilson also of note, I do not have access to a Windows machine to test anything on a Windows environment.
