### ISSUE TITLE
For a returning user, the screen does not go beyond the OAuth screen

### ISSUE THREAD

**Issue by nimishamukherjee** [fabric8io/fabric8-ui#121]
This issue occurs for a returning user:
- On Firefox, I return to the application
- I click on http://console.prod-preview.openshift.io/
- I'm redirected to http://console.prod-preview.openshift.io/signup
- The screen does not proceed beyond this. The text "Please wait, loading user details from OAuth Provider..." is displayed.
- Console screen shot:
![consoleerror](https://cloud.githubusercontent.com/assets/1892722/22873201/681e95fc-f1e4-11e6-9882-c3a39f89b7fc.png)

My system setup:
Firefox 50.1.0
Fedora 25

**Comment by pmuir** [comment]
Dupe of #115 I think.

**Comment by pmuir** [comment]
@nimishamukherjee do you still see this as @joshuawilson thinks he fixed it...

**Comment by joshuawilson** [comment]
I think there are still bugs but I also know that if you delete the cookie for the sight you should be able to login. What I don't know is if that is enough. I don't know if my the changes done with the keys is the cause or if something else is broken. Something to work out over the next several days.

**Comment by pmuir** [comment]
@joshuawilson the other bug was about not having to delete the token from local storage to login... I will reopen.

**Comment by pmuir** [comment]
@nimishamukherjee please retest, as this did work for me.

**Comment by pmuir** [comment]
@nimishamukherjee please retest or I will close ;-)
