### ISSUE TITLE
In Planner, Backlog/Board row in header disappears after saving edits in workitem Detail panel

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-ui#1210]
This is not reproducible at will, but is being seen - when working in the Board view, the header navigation row for Board/Backlog disappears:

It's here:

![screenshot from 2017-04-28 11-41-20](https://cloud.githubusercontent.com/assets/642621/25537057/00ec75b4-2c0b-11e7-9af5-882baf8b42ff.png)

And - now it's gone:

![screenshot from 2017-04-28 11-39-44](https://cloud.githubusercontent.com/assets/642621/25537020/e5d47ea2-2c0a-11e7-9ee9-dff07c2b7bed.png)

**Comment by ldimaggi** [comment]
To recreate - Edit a workitem's detail panel - close the panel and the navigation row disappears.

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-planner#2004
