### ISSUE TITLE
In Planner, moving a workitem to Backlog replaces the workitem's assignee icon

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-ui#1212]
To recreate:
* In Planner backlog view, select a workitem's kebab, and select 'Move to Backlog'
* Observe the workitem's assignee icon replaced with this icon:
![screenshot from 2017-04-28 12-40-01](https://cloud.githubusercontent.com/assets/642621/25538285/1bc717c2-2c10-11e7-8c3f-52962dbec08a.png)

This error is written to the console log in Chrome:

```
Mixed Content: The page at 'https://prod-preview.openshift.io/ldimaggi%2540redhat.com/spaceforalexey/plan/detail/245' was loaded over HTTPS, but requested an insecure image 'unsafe:null&s=23'. This content should also be served over HTTPS.
unsafe:null&s=23:1 GET unsafe:null&s=23 net::ERR_UNKNOWN_URL_SCHEME
```

Before:

![screenshot from 2017-04-28 12-39-11](https://cloud.githubusercontent.com/assets/642621/25538419/a4370b1c-2c10-11e7-9afa-f0109691ae92.png)

After:

![screenshot from 2017-04-28 12-39-30](https://cloud.githubusercontent.com/assets/642621/25538425/abc69b22-2c10-11e7-8f74-046300d5fecd.png)

**Comment by catrobson** [comment]
@ldimaggi - can you log any planner UI issues to the planner repo instead of UI repo moving forward?    https://github.com/fabric8io/fabric8-planner

**Comment by ldimaggi** [comment]
Moved to - https://github.com/fabric8io/fabric8-planner/issues/1835
