### ISSUE TITLE
Space is undefined when launching the app from an incognito browser for the first time

### ISSUE THREAD

**Issue by nimishamukherjee** [fabric8io/fabric8-ui#122]
- Open a fresh instance of Chrome's incognito window
- Login
- Click on a space (BalloonPopGame)
- We get a blank screen
- Console displays "space undefined" error
- After we refresh the incognito window, the UI works as expected
- Screenshot of console error:
![spaceundefined](https://cloud.githubusercontent.com/assets/1892722/22873597/1d561df8-f1e7-11e6-940b-1db89f2cff66.png)

**Comment by pmuir** [comment]
I did a big upgrade to contexts yesterday which Joshua merged, and after that I can''t reproduce, please can you check @nimishamukherjee

**Comment by pmuir** [comment]
@nimishamukherjee please can you check if you still reproduce?
