### ISSUE TITLE
Typos on codebases

### ISSUE THREAD

**Issue by gorkem** [fabric8io/fabric8-ui#1221]
There is a typo on the information box on the codebases page on the `che workspaces` column. Also the che workspace column should just be workspaces. 
![image](https://cloud.githubusercontent.com/assets/82738/25560772/beac2a3e-2d2a-11e7-9149-b686e49e9f76.png)

**Comment by catrobson** [comment]
@gorkem - why should we not say Che - because we would need to say Eclipse Che?

**Comment by catrobson** [comment]
@dlabrecq - as reported in another issue the pop-up ended up with some incorrect grammar.

**Comment by dlabrecq** [comment]
The grammatical error is fixed with https://github.com/fabric8io/fabric8-ui/pull/1200

**Comment by gorkem** [comment]
It is not consistent with the labels we use on the buttons down the list, they are labeled `Create workspace`. Also I think we have the workspace concept on the platform level.

**Comment by joshuawilson** [comment]
@catrobson do we need to change the label or do we keep it with "che"?

**Comment by catrobson** [comment]
We can change it to just "Workspace" to be more consistent.  @mindreeper2420 can you take this?
