### ISSUE TITLE
UI squished in browser view

### ISSUE THREAD

**Issue by rkratky** [fabric8io/fabric8-ui#1222]
Attaching screenshot. Strangely, this only happens when not in incognito mode. Regardless of browser used -- tested in FF, Chromium, Opera, Vivaldi. Squished in regular; OK in incognito.

![ui-squished](https://cloud.githubusercontent.com/assets/6623103/25577456/67e58078-2e66-11e7-9946-fbd9c166e6de.png)

**Comment by joshuawilson** [comment]
Did you change it to be very narrow or did it do that automatically? We do not have it built for mobile sizes yet.

**Comment by rkratky** [comment]
I didn't change the window size (I should've included a screenshot that made it clear). The above squished page is shown in a browser window that's maximized on a 1920px monitor.
![ui-squished](https://cloud.githubusercontent.com/assets/6623103/25608778/9cc580b6-2f1c-11e7-87f9-e6f28ade4f9d.png)

**Comment by joshuawilson** [comment]
@rkratky Can you please verify this is still an issue. If it doesn't occur in incognito, then I am going to guess that you won't be able to reproduce it. However, if you are able to reproduce it, please list the steps here.

@mindreeper2420 any ideas?

**Comment by rkratky** [comment]
@joshuawilson, yes, still the same. But you're right. I've no idea how to reproduce it. I tried with a clean, freshly installed browser (no history, no extensions), and it's still there.

**Comment by joshuawilson** [comment]
@rkratky we just did a major refactor of the UI. Please try again.

**Comment by rkratky** [comment]
@joshuawilson, it now works in an incognito window. The problem is the same in a regular session. I also tried to delete all cache and configs + reinstall Chrome -- so it's a totally fresh session -> still the same problem.

**Comment by joshuawilson** [comment]
That is crazy, it works in incognito but not normal. wow!
Currently you are the only seeing this issue. We will need to figure out more if we are going to fix this.

**Comment by rkratky** [comment]
@joshuawilson, is there any way I can help with it? I'm not sure what to try next.

**Comment by joshuawilson** [comment]
At this point, I can only think of getting into a shared session to see exactly what you have going on.

**Comment by rkratky** [comment]
@joshuawilson, OK, I've no idea what changed, but it works now. Same new installation of the browser, but it's OK now. Apologies for taking up your time.
