### ISSUE TITLE
Intermittent, recurring problem where creating a new project (add to space) results in Forge error

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-ui#1253]
See attached screenshot:

<img width="1920" alt="206e4eda-2c5b-11e7-8b12-4a7fc29d7dd6" src="https://cloud.githubusercontent.com/assets/642621/25730953/94550966-310f-11e7-9692-e816e37b1086.png">

**Comment by ldimaggi** [comment]
I have seen this problem intermittently, where "add to space" fails intermittently. 

For example - creating new project "postsummitspacemay8a" failed on May 8 with this error:

`message = Failed to import project to https://github.com/ldimaggi/postsummitspacemay8a.git. org.eclipse.jgit.api.errors.TransportException: https://github.com/ldimaggi/postsummitspacemay8a.git: 404 Not Found - status = FAILED`

The github repo was created - but was not fully initialized for openshift.io - https://github.com/ldimaggi/postsummitspacemay8a

I have seen this problem intermittently in the past too - is this a timing issue with access to github? A subsequent attempt to create a project was successful.

The full error as displayed to the user was:

======================================================

```
ExecuteForgeCommandError
The forge-quick-start :: execute :: 1 command failed or only partially succeeded

name = ForgeApiServerError
origin = Fabric8ForgeService
message = An unexpected server side forge api error occurred
inner = 
   httpError = 
      status = 500
      statusText = Internal Server Error
      url = https://forge.api.openshift.io/forge/commands/fabric8-new-project/execute
      body = 
         results =  [             
             { 
               status = SUCCESS
             } ,            
             { 
               message = Added Jenkinsfile to project
               status = SUCCESS
             } ,            
             { 
               message = Failed to import project to https://github.com/ldimaggi/postsummitspacemay8a.git. org.eclipse.jgit.api.errors.TransportException: https://github.com/ldimaggi/postsummitspacemay8a.git: 404 Not Found
               status = FAILED
             } ,            
             { 
               message = Created OpenShift BuildConfig ldimaggi/postsummitspacemay8a. Created Jenkins job: https://jenkins-ldimaggi-jenkins.8a09.starter-us-east-2.openshiftapps.com/job/ldimaggi and added git webhooks to repositories postsummitspacemay8a. 
               status = SUCCESS
             } ,            
             { 
               message = Already created BuildConfig ldimaggi/postsummitspacemay8a
               status = SUCCESS
             }  ] 
```

======================================================

**Comment by ldimaggi** [comment]
Also seeing a different variation on this problem: 

`Failed to import project to https://github.com/almightytest/testmay81494272517490a.git. org.eclipse.jgit.api.errors.TransportException: https://github.com/almightytest/testmay81494272517490a.git: https://github.com/almightytest/testmay81494272517490a.git/info/refs?service=git-receive-pack not found`

**Comment by jstrachan** [comment]
I've seen this too - I wonder if the forge wizard server side needs to add a retry around talking to github to create the project and/or importing the code.

BTW I raised an issue here https://github.com/fabric8io/fabric8-generator/issues/9 - if ever the wizard seems to work but errors are returned from the server then we should probably raise those errors here: https://github.com/fabric8io/fabric8-generator/issues/ unless its console or UX related in which case here sounds good!

**Comment by joshuawilson** [comment]
@jstrachan any update?

@mitchharpur what do you think?

**Comment by jstrachan** [comment]
I've added a retry loop around that bit of code. Still not sure why it happens though!

**Comment by jstrachan** [comment]
I'm wondering if its some odd networking issue that sometimes the pod loses the ability to talk to github? does seem like bouncing the pod helps too ;) whenever I've seen this, bouncing the pod and it works great again

**Comment by ldimaggi** [comment]
I think that the cause of this error is:
https://github.com/fabric8io/fabric8-ui/issues/1498

So - we can close https://github.com/fabric8io/fabric8-ui/issues/1253
