### ISSUE TITLE
Enhancement - every ERROR that is logged to Chrome console log should also be reported to the user via the UI

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-ui#1254]
For many error conditions - such as: https://github.com/fabric8io/fabric8-ui/issues/1252 - no error message is displayed in the UI for the user. Unless the user is monitoring the Chrome console log, he/she will not see any details of the error.

It should be a standard that all errors that impact the user are reported in the UI for the user. Thx!

**Comment by joshuawilson** [comment]
@ldimaggi While I do agree with you, I'm not sure how to track this to know that we have completed it. If you want to create a list of errors that don't have messages in the UI, you can list them in the main description and we could treat this as an epic. Or we take it as general advise and close the issue.

**Comment by ldimaggi** [comment]
Let's close this issue - when we see a good (or is it bad   ;-) error that is not handled for the user, we can open up a separate issue for each specific error. Thx!
