### ISSUE TITLE
Pen(cil) icons for editing profile items not working

### ISSUE THREAD

**Issue by rkratky** [fabric8io/fabric8-ui#1255]
Clicking on the pen icons in profile doesn't do anything.
![pen-icon](https://cloud.githubusercontent.com/assets/6623103/25743968/947c3526-3197-11e7-82aa-0fb881d03916.png)

**Comment by joshuawilson** [comment]
The profile page is not active yet.

**Comment by dlabrecq** [comment]
This is an old profile page and that functionality was not implemented, just hard coded.

As of today, the latest profile page is available in prod. Note that the pen icons have been removed as they are not used in the latest mockups.
