### ISSUE TITLE
"Update tenent" -- meant "tenant"?

### ISSUE THREAD

**Issue by rkratky** [fabric8io/fabric8-ui#1256]
In user profile, there a heading and a button that say "Update tenent". What's a "tenent"? Is that supposed to say "tenant"? And if so, what's the difference between the function of this button and "Update Profile"? (Neither of those buttons does anything, btw.)

**Comment by joshuawilson** [comment]
@rkratky I believe you are correct, it is mis-spelled. It updates the OpenShift Tenant.

@catrobson do you have designs for the "update profile"? Do we keep the "update tenant" button and should we have an explanation as to what it does?

**Comment by catrobson** [comment]
This button was put in and does not follow the UX design for profile.  It was told to me that it would be there only temporarily while we were having profile problems, and then it would be removed.

**Comment by joshuawilson** [comment]
@aslakknutsen do you know when we can remove the Tenant button or if we are able to work without it. What needs to happen in the system to not require the user to update their tenant any more?
