### ISSUE TITLE
Profile cannot be updated

### ISSUE THREAD

**Issue by rkratky** [fabric8io/fabric8-ui#1257]
User profile is impossible to update. The "Update Profile" button is grayed out, so there's no way to update info (name, email, etc.) about the user. All I can do is click "Cancel".

Also, clicking on all three links in the left column of the Profile view (Add an email, Add a url, Add a bio) places the cursor (activates) in the "Email" field.

Section "Connected accounts" on the Profile page contains button "Connect GitHub account" and "Connect OpenShift account" -- even though those two accounts have already been connected to the OSIO account in question. The button are not grayed out but clicking the does nothing.

**Comment by dlabrecq** [comment]
This is an old profile page and that functionality was not implemented, just hard coded.

As of today, the latest profile page is available in prod.
