### ISSUE TITLE
"Spaces" tab in user profile not working

### ISSUE THREAD

**Issue by rkratky** [fabric8io/fabric8-ui#1259]
The "Spaces" tab shows the number "2" regardless of the number of spaces the user has. Clicking on the tab shows empty 'space' -- it doesn't show existing spaces the user created, nor does it show the "2" spaces the tab indicates.
![no-spaces](https://cloud.githubusercontent.com/assets/6623103/25744643/4b06e7e8-319b-11e7-8200-676cbc14b5f7.png)

**Comment by rkratky** [comment]
Also, there's placeholder text shown in both the "Spaces" tab ("Static content Spaces") and the "Work Items" tab ("Static content Work items").

**Comment by dlabrecq** [comment]
This is an old profile page and that functionality was not implemented, just hard coded.

As of today, the latest profile page is available in prod. Note there is no longer a count in the tab as we are using infinite scroll.
