### ISSUE TITLE
Cannot refresh the current page

### ISSUE THREAD

**Issue by dlabrecq** [fabric8io/fabric8-ui#1264]
When I click the browser's refresh button, an error is message is shown. For example:
"Cannot GET /dlabrecq%40redhat.com/_update"

This issue also prevents the update profile page from being able to link GitHub and OpenShift accounts properly. For example, when linking GitHub and OpenShift accounts, the user we're forced to redirect to the getting started page. This is because the UI doesn't support refreshing the current page without generating an error.

We need to redirect the user to the current page, but this is not currently possible.

**Comment by joshuawilson** [comment]
@dlabrecq is this fixed? If so, please close this.

**Comment by dlabrecq** [comment]
I no longer see the issue.
