### ISSUE TITLE
java.lang.OutOfMemoryError: Metaspace - reported on build failure

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-ui#1279]
This is a recurring problem - saw this multiple times on May 9 in production.

This pipeline:
https://openshift.io/almusertest1/testmay91494369460731/create/pipelines
https://console.starter-us-east-2.openshift.com/console/project/almusertest1/browse/pipelines/testmay91494369460731?tab=history

Results in this build error:
https://jenkins-almusertest1-jenkins.8a09.starter-us-east-2.openshiftapps.com/job/almightytest/job/testmay91494369460731/job/master/1/console
java.lang.OutOfMemoryError: Metaspace
Finished: FAILURE

For the project in this repo:
https://github.com/almightytest/testmay91494369460731

However - no memory quota issue is reported here:
https://console.starter-us-east-2.openshift.com/console/project/almusertest1/quota

Resource Type	Used	Max
CPU (Limit)	1 core	2 cores
Memory (Limit)	512 MiB	1 GiB

**Comment by ldimaggi** [comment]
Note that the pipelines are reported as not started in the UI.

**Comment by naina-verma** [comment]
Hi @ldimaggi ,

I looks like Quota limit exceed and it is visible on the openshift console as well.

![screenshot from 2017-05-10 12-37-39](https://cloud.githubusercontent.com/assets/19172870/25886947/9187b0d6-357d-11e7-97e4-4b900c3a6a5d.png)
![screenshot from 2017-05-10 12-37-54](https://cloud.githubusercontent.com/assets/19172870/25886946/9187c044-357d-11e7-9a6c-8706663174d9.png)

**Comment by ldimaggi** [comment]
Yes - but - the MEMORY quota is not exceeded.   ;-)

![screenshot from 2017-05-10 08-09-19](https://cloud.githubusercontent.com/assets/642621/25898025/4f424fe4-3558-11e7-86b9-c4eab2873d8d.png)

**Comment by joshuawilson** [comment]
@jstrachan @mitchharpur What do you think?

**Comment by donnydavis** [comment]
I would think its because its out of memory in the meta space
default      1  444  2.9 18011824 2924492 ?    Ssl  02:17  25:57 java -XX:+UseParallelGC -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=100m

Specifically this little fella
XX:MaxMetaspaceSize=100m

This value needs to be increased

Open a shell on your jenkins pods and do a ps aux

**Comment by donnydavis** [comment]
A quick search brings me back to here
https://github.com/openshift/jenkins/blob/master/2/contrib/s2i/run#L65
and here
https://github.com/openshift/jenkins/blob/master/slave-base/contrib/bin/run-jnlp-client#L86

The values are hard coded when the upstream image is built. 

I already opened an issue 
https://github.com/openshift/jenkins/issues/296

Cheers

**Comment by donnydavis** [comment]
It would appear you can override this value by adding this env variable to your dc
JAVA_GC_OPTS

**Comment by jstrachan** [comment]
@rawlingsj any thoughts?

**Comment by ldimaggi** [comment]
Closing as not reproducible
