### ISSUE TITLE
Routing should redirect to login page for bookmark-able URLs

### ISSUE THREAD

**Issue by corinnekrych** [fabric8io/fabric8-ui#1289]
similar to issue https://github.com/fabric8io/fabric8-ui/issues/1246 the following URL should have a routing that forward to login page if user is not logged in:
http://localhost:3000/username/space
http://localhost:3000/username/space/plan
http://localhost:3000/username/space/plan/detail/311 (a workitem id)
http://localhost:3000/username/space/create/pipelines 
http://localhost:3000/username/_spaces
http://localhost:3000/username

Note: those are forwarding to login page as expected:
http://localhost:3000/_home OK
http://localhost:3000/username/space/create OK

**Comment by joshuawilson** [comment]
We do have a doc that breaks that down, though it doesn't mean they are fixed yet. Still much work to do there. 

https://docs.google.com/spreadsheets/d/1cNSDuek0v1EBPpdPlFwG_Y_yOlux86m9MYf9UrF82l4/edit#gid=208615194

**Comment by joshuawilson** [comment]
For most of the URLs we should NOT redirect to the Login page but only prevent the user from editing. If they want to edit it, they need to login. We need to get @fabric8io/uxd to provide guidance on it.

**Comment by catrobson** [comment]
+1 that most of the pages should not re-route to log-in when the user is just viewing and we'll need to ask for log-in only upon edit.  I'll add a story to the UX backlog to designate log-in points across the platform.

**Comment by joshuawilson** [comment]
Thanks @catrobson

**Comment by joshuawilson** [comment]
All of the listed links should still display even when not logged. There is another issue for determining what needs to be restricted when not logged in at #139.
