### ISSUE TITLE
use relative url's rather than fqdn's for dependancy services

### ISSUE THREAD

**Issue by kbsingh** [fabric8io/fabric8-ui#129]
* **I'm submitting a ...**
[X] feature request

* **What is the current behavior?**
https://github.com/fabric8io/fabric8-ui/blob/master/cico_build_deploy.sh#L19 specifies an absolute URL to be used for a dependancy service.

* **What is the expected behavior?**
Move to using relative urls eg : api.<domain of fabric8-ui>, and sso.<domain of fabric8-ui> etc 

* **What is the motivation / use case for changing the behavior?**
This allows the same code to be portable between run environments, without the need to rebuild for each instance.

* **Please tell us about your environment:**
OpenShift Origin 1.4

- Angular version: 2.0.0-beta.X
- Browser: [all  ]

**Comment by sbose78** [comment]
Hi @kbsingh Sorry if this is a very fundamental question, 
The name of the environment ( "demo.almighty.io" ) would be passed on an env variable to cico_build_deploy.sh ?
Is that the expectation?

**Comment by kbsingh** [comment]
@sbose78 no, there would be / should be nothing passed in via the Env at build time, the code should be able to make assumptions around where to find the various end points. eg. in your example of demo.almighty.io, if the ui code was running on www.almighty.io, it should assume that the sso is at sso.almighty.io and api is at api.almighty.io; similarly moving it to mydevbox.io should make it look for sso at sso.mydevbox.io; and be able to do this without needing a rebuild.

**Comment by pmuir** [comment]
@sbose78 should we assign this one to you?

Offline discussion:
> @aslakknutsen says  remove API_URL and assume sso. + " window.location.host ('generally', not specifically)

Core issue is https://github.com/almighty/almighty-core/issues/775

**Comment by alexeykazakov** [comment]
To be clear. This issue is about using relative URL's in UI for dependency services. For UI these services are almighty-core, planner etc.
UI currently doesn't use Keycloak (sso.*) service directly. The keycloak/sso part is for the core side - almighty/almighty-core#775
But if we start using Keycloak directly in UI then yes, it should use the relative URL for that too.

**Comment by pmuir** [comment]
Ok, now I understand.

**Comment by sbose78** [comment]
Thanks @pmuir @kbsingh and @alexeykazakov 
Wanted to add that : 
I don't think we should be doing away with the env or API_URL argument approach completely since it helps when trying out things in local.

The code should use relative URLs ( as required by this issue ) as a default , but use env var if they are present.

**Comment by kbsingh** [comment]
@sbose78 can that be made optional ? so use API_URL if its exists, otherwise default to api.<domain>/

**Comment by alexeykazakov** [comment]
@sbose78 completely agree with you. This is what I'm going to implement in almighty-core. Use the relative URL's by default but you still can override it by passing the absolute URL's via configuration/env vars. We need it for testing stuff in dev environment.

**Comment by pmuir** [comment]
@sbose78 @kbsingh that was my idea - I'll add an api service to the UI that we can share with other components.

**Comment by sbose78** [comment]
Yes @kbsingh .
@alexeykazakov Are you working on it? If yes, let me know if you need to split up tasks with me.

**Comment by alexeykazakov** [comment]
@sbose78 I'm working on the core part only - https://github.com/almighty/almighty-core/issues/775
Not on this one which is the UI part.

**Comment by pmuir** [comment]
@kbsingh @aslakknutsen @sbose78 @alexeykazakov fabric8-ui is updated to look at relative URLs for services but I have left the hard-coding in the prod build for now until you tell me the services are appearing at the right URLs (I need work item tracker and bayesian right now).
