### ISSUE TITLE
Invalid link to Home from the pipeline history page

### ISSUE THREAD

**Issue by joshuawilson** [fabric8io/fabric8-ui#1345]
_From @fbricon on May 2, 2017 15:28_

Clicking on the `Home` link from the Pipeline history (`https://openshift.io/<user>/<space>/create/pipelines/<repo>/history`) page fails:

<img width="946" alt="screen shot 2017-05-02 at 11 25 33 am" src="https://cloud.githubusercontent.com/assets/148698/25625313/2fdc9a12-2f2a-11e7-9a08-2820d0c7e90c.png">

_Copied from original issue: openshiftio/openshift.io#133_

**Comment by corinnekrych** [comment]
@joshuawilson I don't see any breadcrumbs like in screenshot beside according to 
https://github.com/fabric8io/fabric8-ui/blob/master/src/app/create/pipelines/pipelines-routing.module.ts
there is no https://openshift.io/<user>/<space>/create/pipelines/<repo>/history
actually clicking on the repo itself forward to 404
should we close this issue?

**Comment by joshuawilson** [comment]
@corinnekrych I think we either need a new issue for what you recorded or fix that first and then see if we still have the recorded bug.

@fbricon can you still reproduce this issue?

**Comment by fbricon** [comment]
Still there on openshift.io: https://www.screencast.com/t/4B0OTyDOMDa

**Comment by joshuawilson** [comment]
@fbricon do you have a way to see that without Flash?

**Comment by joshuawilson** [comment]
@catrobson can you tell us what this should do since we can't repoduce it and don't know which way to make it go?
@jstrachan do you remember what it is supposed to do?

**Comment by corinnekrych** [comment]
This path https://openshift.io/<user>/<space>/create/pipelines/<repo>/history is not valid any more in the router. We can't even go to:
https://openshift.io/<user>/<space>/create/pipelines/<repo>, an error page is displayed. what should be the correct behaviour? Should be have a link on pipe and then one on pipe history or should we disable the link on pipe all together?

**Comment by joshuawilson** [comment]
@corinnekrych it looks like you have 3 slashes in the middle of the URL, is that intentional?

**Comment by corinnekrych** [comment]
@joshuawilson sorry md issue, I've fixed it.

**Comment by fbricon** [comment]
@joshuawilson HIH


![jun-12-2017 09-51-29](https://user-images.githubusercontent.com/148698/27037064-c7b51928-4f54-11e7-837a-d8eac105608a.gif)

**Comment by joshuawilson** [comment]
@catrobson do you know what you want us to do with this screen yet?

**Comment by jstrachan** [comment]
fixed by https://github.com/fabric8-ui/fabric8-runtime-console/pull/
