### ISSUE TITLE
OpenShift project is not accecible

### ISSUE THREAD

**Issue by joshuawilson** [fabric8io/fabric8-ui#1354]
_From @chmouel on May 5, 2017 7:35_

Maybe I am missing some things but when creating a new space I am getting this error : 

![image](https://cloud.githubusercontent.com/assets/98980/25737056/f85357ae-3175-11e7-88fa-c2a7da49d10b.png)

_Copied from original issue: openshiftio/openshift.io#155_

**Comment by jstrachan** [comment]
think this was to do with init-tenant not creating the default namespace?

**Comment by joshuawilson** [comment]
@chmouel are you still seeing this?

**Comment by chmouel** [comment]
Yep this has been resolved with a fix to almighty with login
synchronization, we can close this thanks
