### ISSUE TITLE
Creating a new space doesn't filter Github repos properly

### ISSUE THREAD

**Issue by joshuawilson** [fabric8io/fabric8-ui#1367]
_From @fbricon on May 2, 2017 15:17_

I can't type my repository name in the filter field, it's readonly apparently. Which forces me to scroll through my hundreds of repo.
<img width="572" alt="screen shot 2017-05-02 at 11 13 06 am" src="https://cloud.githubusercontent.com/assets/148698/25624880/ce75c240-2f28-11e7-9ab1-c77d98549774.png">

Moreover, all repositories display the same hard-coded description (`The regexp pattern to match the repository name`)

_Copied from original issue: openshiftio/openshift.io#131_

**Comment by jstrachan** [comment]
@mitchharpur I wonder if we could use that nice new multi-select widget you created? I could make the forge wizard take a list of projects to choose from if that helps?

**Comment by joshuawilson** [comment]
@mitchharpur can you please pass that info to @corinnekrych

**Comment by jstrachan** [comment]
this one is fixed - I just need a new fabric8-ui release in prod before I update to the new back end

**Comment by joshuawilson** [comment]
@jstrachan I think the release you are waiting on is done.

**Comment by mitchharpur** [comment]
the multi select widget seems like a good candidate

**Comment by jstrachan** [comment]
@mitchharpur agreed - fixed it and used it thanks! :)
