### ISSUE TITLE
Use the new `Number` attribute to display a work item number

### ISSUE THREAD

**Issue by xcoulon** [fabric8io/fabric8-ui#1387]
Once https://github.com/almighty/almighty-core/pull/1338 has been merged, the work items structure will be changed in the backend and in the REST API: internally, we'll use a `UUID` as the unique identifier of a work item in the whole system, and a new field named `number` will contain the work item's 'natural id' in the parent space. This is the field that should be used in the UI when displaying the work item number, instead of the `ID` field. 

Here's an example of the response for a `GET /api/spaces/<space_id>/workitems/<work_item_id>` response:

````json
{
	"data": {
		"attributes": {
			"system.created_at": "2017-05-24T08:17:49.249533Z",
			"system.number": 33,
			"system.order": 34000,
			"system.remote_item_id": null,
			"system.state": "new",
			"system.title": "Updated Test WI",
			"system.updated_at": "2017-05-24T08:17:49.265577Z",
			"version": 1
		},
		"id": "97e70e16-8d3f-428b-bff1-7d974186bedd",
		"links": {
			...
		}
	}
}
````
which includes the new `system.number` attributes element to use in replacement of the `id` element.

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-planner#1925

**Comment by joshuawilson** [comment]
This is a task for the Planner team, passed it over to them. cc @michaelkleinhenz
