### ISSUE TITLE
'Connect OpenShift account' button doesn't work

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8-ui#1406]
My OpenShift token timed out or something so I wanted to re-connect it.  Clicking the button doesn't seem to have any affect.

![screenshot 2017-05-26 10 42 44](https://cloud.githubusercontent.com/assets/1457180/26489643/17bccb76-4200-11e7-998f-1ddc9357bd92.png)

**Comment by sbose78** [comment]
@dlabrecq could you please take a look? I see, no requests are being sent to the backend for these 2 buttons.

**Comment by rawlingsj** [comment]
@alexeykazakov @aslakknutsen it's probably a separate discussion but I'm wondering if we can automate the openshift token refresh?  That would prevent the error altogether and avoid users having to take this manual step?

**Comment by dlabrecq** [comment]
Those particular buttons appears to be from the old profile page. Until a couple days ago, the new profile page had not been merged to prod, only prod-preview. However, I just checked prod and the lastest profile page is available now.

**Comment by dlabrecq** [comment]
FYI, if you had logged out successfully, the user should be redirected to the getting started page upon a new login. The getting started page asks the user to link their accounts.

**Comment by alexeykazakov** [comment]
OSO doesn't support token refresh. But we could re-link users OSO account which should obtain a new valid OSO token for the user - https://github.com/almighty/almighty-core/issues/1351
We should make sure we have all needed API on the SSO/API service side then we can address it on the UI level.

**Comment by joshuawilson** [comment]
The UX has been changed and this is not viable, closing.
