### ISSUE TITLE
Not working "Plan out my space" and "Create new code from scratch" in welcome popup

### ISSUE THREAD

**Issue by joshuawilson** [fabric8io/fabric8-ui#1417]
_From @danieloh30 on May 29, 2017 13:37_

During creating new space, we can see the popup window as below screenshot. But when we click icons related to "Plan out my space" and "Create new code from scratch", it's not working but only "Import exist code" and "Select technology stack and pipeline" . 

![screenshot from 2017-05-29 22-33-37](https://cloud.githubusercontent.com/assets/14066977/26551742/e740010e-44be-11e7-985f-d3e6cea09c92.png)

_Copied from original issue: openshiftio/openshift.io#185_

**Comment by jstrachan** [comment]
should `Plan out my space` just be the same as clicking on the `Plan` tab for now? Though it sounds odd having a massive button; when after the dialog closes you get to click on `Plan` on the nav bar anyways?

**Comment by joshuawilson** [comment]
@mitchharpur what was your intent here?
We also need help from @fabric8io/uxd on this.

**Comment by joshuawilson** [comment]
Any update @mitchharpur

**Comment by mitchharpur** [comment]
For "Plan out my space'
Yes. Plan out my space is just navigating to the planner... that is the intent... no more ... no less ... and that based on Todd's original spec ... It is no doubt a redundant button.

For 'code from scratch' ... 
The intent was to have a forge command that creates an empty repo/codebase and then open che in the repo

**Comment by joshuawilson** [comment]
Thanks @mitchharpur 

@qodfathr can you provide guidance on these 2 button in the wizard.
cc @catrobson

**Comment by catrobson** [comment]
+1 to Mitch's description.   "Plan out my space" should bring me into the planner to start adding work items.  "Code from Scratch" should bring me right into an IDE to start working as described.

**Comment by joshuawilson** [comment]
@qodfathr the PR #1590 removes those 2 buttons/features. Do you want to keep them?

**Comment by qodfathr** [comment]
We can remove from now. FWIW, the original intent was:

Plan my space -- just navigate to Planner.
Start from scratch -- basically, just set up a new, empty codebase, create the workspace, and navigate directly into Che.
