### ISSUE TITLE
Pipelines view blank

### ISSUE THREAD

**Issue by joshuawilson** [fabric8io/fabric8-ui#1436]
_From @luebken on June 2, 2017 14:9_

- I've switched to the pipelines tab.
- Started a new pipeline via the kebab menu.
- As nothing happend I refreshed the page. 
- The resulting page was blank.

<img width="1348" alt="screen shot 2017-06-02 at 16 03 28" src="https://cloud.githubusercontent.com/assets/53055/26729419/dc4a9a1a-47ad-11e7-9f31-6e33cdbc2890.png">

_Copied from original issue: openshiftio/openshift.io#189_

**Comment by jstrachan** [comment]
My guess is its an openshift token issue - logging out and in again (or reconnecting your openshift account) will fix it. 

I wonder what gets returned on the Network tab if you filter with `buildconfigs` - it looks like HTML or something is being returned instead of JSON from the error log.

I've no idea why the openshift tokens keep going stale though - its a bigger issue really - we need to stop that happening if we can

**Comment by jstrachan** [comment]
if its your openshift token thats no longer connected you could try relink your openshift token:

* click on your user name (top right) and a drop down occurs
* select Profile
* click "Update Profile" button on the top right
* click the "Connect OpenShift" button near the bottom of the page

If that doesn't work/fix it, you could try 
* go to this URL:  https://sso.openshift.io/auth/realms/fabric8/account/identity
* login
* click `Remove` next to the OpenShift identity if you can
* click `Add` for the OpenShift identity

**Comment by pkettman** [comment]
My pipelines list is unexpectedly blank as well, but but different errors in the JS console.
![obrazek](https://cloud.githubusercontent.com/assets/26871874/26780673/1db8550c-49eb-11e7-9451-09ead7462943.png)

**Comment by jstrachan** [comment]
through chat it turned out that @pkettman's openshift identity wasn't even connected to his keycloak account as the 'Remove' button didn't appear here https://sso.openshift.io/auth/realms/fabric8/account/identity

**Comment by joshuawilson** [comment]
@luebken did you get this resolved?

**Comment by luebken** [comment]
@joshuawilson It works for me now. If it is resolved I can not answer since I don't know the underlying problem.

**Comment by joshuawilson** [comment]
Thanks, closing this.
