### ISSUE TITLE
App Wizard: hide the 'labelSpace' and 'kubernetesSpace' properties on the `Select a build pipeline strategy` wizard tab

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-ui#1441]
I'm just about to move these 2 properties to the ChoosePipelineStep wizard step to fix the spaces / labels issue so they now appear at the bottom of the UI as shown below. Lets hide them if they are there too (like we do currently on the next step)
<img width="887" alt="fabric8" src="https://cloud.githubusercontent.com/assets/30140/26780320/26c6287c-49e1-11e7-8f5a-e0a5ea1c4b6f.png">

**Comment by catrobson** [comment]
UXD has a story to look at the whole wizard, but in the meantime this is a bit of a visual mess to look at and understand what is happening.  Some suggestions below.

![pipelinestrategypage](https://cloud.githubusercontent.com/assets/3739227/26783243/31a3025e-49c5-11e7-95e8-f89cb79e5f03.jpg)
