### ISSUE TITLE
Conflict between keycloak username and OSIO username

### ISSUE THREAD

**Issue by chmouel** [fabric8io/fabric8-ui#1442]
We are trying to investigate why the UI on OSIO is trying to create things as _cboudjna-_ when my username is _chmouel_ from the UI.

We have updated the keycloak information to make sure it's configured as cboudjna as show on this screenshot

![image pasted at 2017-6-5 16-07 1](https://cloud.githubusercontent.com/assets/98980/26787816/93482426-4a0b-11e7-967d-4528cadc97b1.png)

after logout/login clear using a private session I am still getting referenced username as chmouel : 

![image pasted at 2017-6-5 16-07](https://cloud.githubusercontent.com/assets/98980/26787884/cab58a2a-4a0b-11e7-97f3-bbf9d87bf61a.png)

Which then fails for other operations for example when creating spaces I am getting this error : 

![image pasted at 2017-6-5 15-36](https://cloud.githubusercontent.com/assets/98980/26787940/edb3b5ba-4a0b-11e7-9fd3-d6e123c3b96f.png)

**Comment by sbose78** [comment]
After login/logout, the keycloak username does not get sync'd because currently we only sync from OSIO --> Keycoak and not the other way around. 

The initial username is stored in the api.openshift.io backend.

**Comment by alexeykazakov** [comment]
Users are not supposed to use KC UI at all and specially for updating their profiles. We will block KC UI for users later.
But anyway, in this case the login-logout didn't help. @sbose78 could you please take a look why?

**Comment by sbose78** [comment]
We don't update the username, we only update full-name, email and avatar.

https://github.com/almighty/almighty-core/blob/master/login/service.go#L700

**Comment by alexeykazakov** [comment]
Related to https://github.com/almighty/almighty-core/issues/1366

**Comment by chmouel** [comment]
This seems to be fixed for me as I don't have any errors anymore, I think we can close this
