### ISSUE TITLE
Service "12-vertxbasic" is invalid: metadata.name: Invalid value:

### ISSUE THREAD

**Issue by joshuawilson** [fabric8io/fabric8-ui#1454]
_From @burrsutter on June 6, 2017 13:20_

Projects that begin with numbers fail in the Integration Test phase of the Jenkins build.

https://gist.github.com/burrsutter/f48fac019c3e3b371d9f51b9b212ee91

Workaround is to put the numbers later in the string like "vertx12basic".  The reason I moved the numbers earlier in the string is because the back end of the string is cut-off in the UI.

https://screencast.com/t/ilxblIBSplA

_Copied from original issue: openshiftio/openshift.io#193_

**Comment by joshuawilson** [comment]
_From @jstrachan on June 6, 2017 13:23_

yeah - the wizard should disallow project names starting with numbers as they are invalid as kubernetes names for things like services

**Comment by jstrachan** [comment]
added better validation in forge
