### ISSUE TITLE
Space Applications Dashboard never populates (despite the Applications tab populating)

### ISSUE THREAD

**Issue by joshuawilson** [fabric8io/fabric8-ui#1475]
_From @burrsutter on June 8, 2017 9:41_

on the Analyze/Space Dashboard
https://screencast.com/t/LodwWToA9J
https://screencast.com/t/ZkGecTDMc

_Copied from original issue: openshiftio/openshift.io#209_

**Comment by dgutride** [comment]
This work is complete - moving to closed
