### ISSUE TITLE
Quickstart - Import code - different users are seeing different import options

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-ui#1491]
See the atatched screenshots - it looks the user is asked to specify an organization, only if the user is already in one or more github organizations:

![screenshot from 2017-06-09 15-53-21](https://user-images.githubusercontent.com/642621/26994392-7ac8f844-4d35-11e7-8af0-6d917dc271f7.png)
![screenshot from 2017-06-09 15-50-00](https://user-images.githubusercontent.com/642621/26994393-7acd86ac-4d35-11e7-88ec-83382dbcb376.png)

However - our test account does belong to one organization, and that user is not asked to specify an organization:

![screenshot from 2017-06-09 16-56-23](https://user-images.githubusercontent.com/642621/26994425-9e3d0b44-4d35-11e7-893b-5b7678841ffb.png)

**Comment by ldimaggi** [comment]
The same problem is being seen tody - even though the "almightytest" user us now a member of 2 organizations.

What is the threshold for a user account to trigger/see the organization option when importing code for a new project? Thx!

**Comment by burrsutter** [comment]
Here are my organizations - what openshift.io sees and what is on github are not in sync
<img width="559" alt="github_organizations" src="https://user-images.githubusercontent.com/378310/27013568-4144332e-4eb4-11e7-8d47-040ac3fb9f53.png">
<img width="901" alt="import_organizations" src="https://user-images.githubusercontent.com/378310/27013567-4140105a-4eb4-11e7-8929-dafe898c7d55.png">

**Comment by burrsutter** [comment]
And the repository name pattern drop-down list is not accurate for the organization I picked on the first step.  The burrsutter organization does not have these repositories

<img width="896" alt="repository_name_pattern2" src="https://user-images.githubusercontent.com/378310/27013594-c1a8e686-4eb4-11e7-96dc-ef4901c44327.png">

**Comment by corinnekrych** [comment]
The root cause is linked to https://github.com/fabric8io/fabric8-generator/issues/17
