### ISSUE TITLE
Sizing of Create Space / App Wizard is inconsistant

### ISSUE THREAD

**Issue by joshuawilson** [fabric8io/fabric8-ui#1517]
If you use the context menu or the link on the home dashboard for "Create Space", you get a very wide pop-up window. 

If you go into "View All Spaces" and click the "add" button at the top it displays a narrow version.

**Comment by mindreeper2420** [comment]
@joshuawilson I'll take care of this once PR https://github.com/fabric8io/fabric8-ui/pull/1419 is merged and available.

**Comment by joshuawilson** [comment]
sounds good, thanks

**Comment by mindreeper2420** [comment]
@joshuawilson This should be fixed as part of PR #1419.
