### ISSUE TITLE
Update Navigation for Multiple Screen Sizes

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8io/fabric8-ui#1529]
Currently, the navigation hides elements when the user views the UI on a screen smaller than 1024px. According to the PatternFly/Bootstrap framework, the navigation should respond by moving the links into a hamburger menu and provide a user with the ability to open the menu with a button.

This story is to address that issue, converting the custom navigation bar into an extended Bootstrap navbar. All visuals and interactions (aside from the <1024px view) will remain the same.

**Requires the following work to be completed:**
- requires https://github.com/fabric8io/fabric8-ui/pull/1419

**Verification Conditions:**
- Navigation is usable on devices narrower than 1024px
- Visuals and interactions are unchanged from primary behavior

**Additional:**
- Designs and code are shared with fabric8-planner, in order to keep consistency between modules

**Comment by joshuawilson** [comment]
related to https://github.com/fabric8io/fabric8-ui/issues/365

**Comment by mindreeper2420** [comment]
navigation updated on the current framework - will convert to the new framework (PR #1419) once merged.
