### ISSUE TITLE
Pipelines continue to be seen in OSIO - even after they have been deleted in OpenShift

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-ui#1532]
See the attached screenshots - the pipelines in question were deleted through the OpenShift console, but they continued to be seen in the OSIO UI - even after that UI was refreshed:

![screenshot from 2017-06-16 11-37-50](https://user-images.githubusercontent.com/642621/27235789-3459efd4-5290-11e7-97c0-fb2301b8c938.png)
![screenshot from 2017-06-16 11-37-30](https://user-images.githubusercontent.com/642621/27235790-34697544-5290-11e7-93a3-2ace18b5b169.png)

**Comment by joshuawilson** [comment]
@jstrachan did you say you already had an issue for this?

**Comment by jstrachan** [comment]
fixed in the latest tenant. Now deleting a Pipeline removes the project name from the Jenkins Github Org job
