### ISSUE TITLE
Remove dummy data/fake screens

### ISSUE THREAD

**Issue by joshuawilson** [fabric8io/fabric8-ui#1533]
_From @maxandersen on June 16, 2017 12:37_

_Copied from original issue: openshiftio/openshift.io#246_

**Comment by joshuawilson** [comment]
_From @qodfathr on June 16, 2017 12:44_

I think I only see 1 remaining: Developer Poll (https://openshift.io/_home)

**Comment by joshuawilson** [comment]
@catrobson do you have any ideas what to put in for the Developer Poll?

**Comment by catrobson** [comment]
Documentation is not live, so link on homepage goes to 404: https://access.redhat.com/documentation/en-us/red_hat_openshift.io/1/html-single/user_guide

**Comment by catrobson** [comment]
For developer poll, can we replace with an Recent Active Pipelines widget that shows me the 5 most recent *currently in progress* or *failed* pipelines across my spaces.

**Comment by catrobson** [comment]
@dgutride and @dlabrecq - can you and I work on this today to see if we can resolve any dead links and information?

**Comment by joshuawilson** [comment]
related to #1348

**Comment by dlabrecq** [comment]
Yes, the dev poll is fake / hard coded. Just something to fill space for summit.
