### ISSUE TITLE
create Workspace should reuse the `stackId` property on the Codebase 

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-ui#1547]
we will be passing in the `stackId` shortly when creating new projects passing the returned value from Forge (https://github.com/fabric8io/fabric8-ui/issues/1546).

We need to reuse this value when creating the Workspace to then associate the correct stack id with the che workspace

**Comment by corinnekrych** [comment]
should be done with https://github.com/fabric8io/fabric8-ui/pull/1580
