### ISSUE TITLE
Can't leave a space on first click, View all spaces is empty

### ISSUE THREAD

**Issue by joshuawilson** [fabric8io/fabric8-ui#1553]
Login
go to a space
try to go to View All Spaces or your Profile (this results in a error that prevents you from navigating away)
try again and it should work
the View All Spaces is now empty
refresh and it fills in the list of spaces

**Comment by dgutride** [comment]
@joshuawilson - work complete, moving to closed (unless you'd like to add a new status tag of status/verify)
