### ISSUE TITLE
Create new project (quickstart) dialog - final page display is malformatted

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-ui#1561]
First started seeing this on June 2.

To recreate:
* Create a new (quickstart) project - accept all defaults

![format](https://user-images.githubusercontent.com/642621/27390092-50528cf0-566e-11e7-919b-5bdf1a6aa218.jpg)

**Comment by joshuawilson** [comment]
@corinnekrych and @mindreeper2420 please take a look.

**Comment by joshuawilson** [comment]
duplicates #1558

**Comment by mindreeper2420** [comment]
I'm unable to verify this, as the wizard always fails for me. I know that it revolves around how the labels/inputs are styled.

**Comment by ldimaggi** [comment]
Stop on by and I can show you the error Adam...
