### ISSUE TITLE
Refresh token to avoid access token experation

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8io/fabric8-ui#157]
We need to refresh token if user is active. Otherwise the token will be expired and the user will be redirected to the login page.
Backend has all needed support for that:
https://github.com/almighty/almighty-core/pull/776
https://github.com/almighty/almighty-core/pull/780

I know that @dgutride is working on this but I didn't find any open UI issue for that. Sorry if it's a duplicate.

**Comment by pmuir** [comment]
@dgutride please self assign if you are working on this.

**Comment by dgutride** [comment]
@pmuir - I'm not able to assign myself, can you add me to the fabric8io org?

**Comment by dgutride** [comment]
https://github.com/fabric8io/fabric8-ui/pull/194 - ngx-login-client was updated to auto refresh the token prior to expiration.  Closing...
