### ISSUE TITLE
Add to Space Wizard: only options are Import and New Quickstart right now?

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-ui#1578]
when clicking the `Add to space` button the only 2 options we have right now are import git repo and new quickstart right now?

we've 4 buttons today; wonder if we should hide 2 for now to make it easier to grok?

**Comment by joshuawilson** [comment]
duplicates #1487 #1417

**Comment by jstrachan** [comment]
I'm not sure they are quite the same thing. There's the Create space wizard and the Add to space wizard - today they are the same but I'm not sure they should be.

When creating a space we probably need 3 options; `Plan, Import, Quickstart`

Once we have a space, the `Add to Space` should only show `Import & Quickstart` - since the Forge wizard doesn't help Plan anything, you use the Plan tab for that

**Comment by joshuawilson** [comment]
I agree, let's remove them for now. Then add them back in when they work.
