### ISSUE TITLE
Add a collaborator to a space

### ISSUE THREAD

**Issue by VineetReynolds** [fabric8io/fabric8-ui#172]
**Description**

As a project owner, I'd like to add a collaborator to a space, so that I can collaborate with other team members on a specific project.

When adding a collaborator, the collaborator should be identified uniquely as a user in the system.

**Functional Acceptance Criteria:**

* The collaborator should see the space under the list of spaces he is collaborating on.
* The space should register the new collaborator in a list of collaborators.

**Comment by ldimaggi** [comment]
Question - Do we also want the ability to revoke a collaborator's membership in a team? If we do this, what will happen to his/her access to workitems, comments, etc. that she created? Thx!

**Comment by alexeykazakov** [comment]
related to https://github.com/almighty/almighty-core/issues/762

**Comment by catrobson** [comment]
Wireframes for adding collaborators to space:
https://redhat.invisionapp.com/share/7XAIMZBBK#/230302872_Space_Setting_Collab_0

**Comment by joshuawilson** [comment]
This appears done, closing.
