### ISSUE TITLE
Login fails at times

### ISSUE THREAD

**Issue by pmuir** [fabric8io/fabric8-ui#174]

**Comment by dgutride** [comment]
@pmuir - any insight into how to repro this?  I think my fix here https://github.com/fabric8io/fabric8-ui/pull/192 cleaned up the oddities with the initial login when either a good or bad token is existing.

**Comment by pmuir** [comment]
No, let's leave this open and if we spot anything, add it?

**Comment by pmuir** [comment]
This seems to be sorted out.
