### ISSUE TITLE
Chrome browser issues - some screen elements are showing up blank

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-ui#179]
Just started seeing this today - see attached screenshots - to recreate:

* Build from source, access localhost:3000
* Navigate UI screens - observe blank UI elements
* Navigating to the "learn" screen seems to clear this up
* Problems are being seen on RHEL7 with Chrome Version 54.0.2840.59 (64-bit)

![screenshot from 2017-02-22 10-38-38](https://cloud.githubusercontent.com/assets/642621/23219106/26dbe1c6-f8ec-11e6-923c-c979c1c2bfbc.png)
![screenshot from 2017-02-22 10-38-09](https://cloud.githubusercontent.com/assets/642621/23219105/26dbdc4e-f8ec-11e6-837a-be5af61b8a17.png)

**Comment by pmuir** [comment]
@mitchharpur @dgutride either of you know what is up here.

**Comment by dgutride** [comment]
@pmuir - the styles appear to be loading too late - I noticed quite a few scss changes coming in shortly, I'd like to wait to debug until those are complete because it could all be related.

**Comment by pmuir** [comment]
I think https://github.com/fabric8io/fabric8-ui/pull/188 may well fix it @dgutride

**Comment by pmuir** [comment]
@ldimaggi can you please check this on current HEAD of master or http://prod-preview.openshift.io as I think this is fixed.

**Comment by ldimaggi** [comment]
Closing - verified as fixed in master.
