### ISSUE TITLE
Replace angular 2 flash messages

### ISSUE THREAD

**Issue by pmuir** [fabric8io/fabric8-ui#184]
This is where we should integrate the toast notifications IMO

**Comment by pmuir** [comment]
@dgutride @dlabrecq @joshuawilson do we have plans to add toast-notifications to ngx-widgets?

**Comment by dlabrecq** [comment]
Angular Patternfly has pfToastNotification and pfToastNotificationList available. I'm guessing we would want the list functionality, too? 

http://www.patternfly.org/angular-patternfly/#/api/patternfly.notification.component:pfToastNotificationList

Would you like us to convert these components to Angular 2?

**Comment by pmuir** [comment]
I would but I defer to Joshua on priorities...

**Comment by dlabrecq** [comment]
Converted the Angular Patternfly toast notification. Working on the notification list which uses it.

https://github.com/fabric8-ui/ngx-widgets/pull/9
