### ISSUE TITLE
Allow user to navigate + log in to their home page via cut and paste  or type entering URL

### ISSUE THREAD

**Issue by Mgranfie** [fabric8io/fabric8-ui#242]
@pmuir 
As a user of OpenShift.io I want to be able to paste or type my URL "openshift.io/<myusername>" into the browser and if I am not yet logged in, I am directly navigated to the RHD login, so that I don't have to click the "Log in" option/button on the OS.io beta page every time I want to log in to OS.io.

**Comment by pmuir** [comment]
@Mgranfie could you open this in https://github.com/openshiftio/www.openshift.io please?

**Comment by Mgranfie** [comment]
@pmuir Yes will do.

**Comment by Mgranfie** [comment]
This was moved to OpenShift.io
