### ISSUE TITLE
Can't logout

### ISSUE THREAD

**Issue by joshuawilson** [fabric8io/fabric8-ui#260]
From being logged, I can not log out. If I want to switch accounts or users I have to wait for some unknown timeout to occur. 

We need to be able to actually log out when you click "logout".

**Comment by alexeykazakov** [comment]
I created an issue for backend - https://github.com/almighty/almighty-core/issues/987

**Comment by alexeykazakov** [comment]
We now have a new endpoint in api:
GET /api/logout
Optional param: `redirect=<encodedURL>`, if not set then referrer will be used to redirect to after logout.
Please use it to logout users :)

**Comment by joshuawilson** [comment]
Thanks @alexeykazakov, @dgutride when you get time, please update this.
