### ISSUE TITLE
Space creation default button closes modal

### ISSUE THREAD

**Issue by joshuawilson** [fabric8io/fabric8-ui#266]
When I create a new space the first screen that pops up is for entering the name. If I type the name and hit enter it closes the screen. 

We need to get @fabric8io/uxd to think about what it should do, but I know it shouldn't close.

**Comment by pmuir** [comment]
@Essjaysee is working on this and I've seen first versions of mockups that change the UX flow.

**Comment by Essjaysee** [comment]
https://redhat.invisionapp.com/share/ZQARDX35J if you'd like to take a look, @joshuawilson

**Comment by joshuawilson** [comment]
@Essjaysee thanks, for the link. Additionally I really like the Space Wizard image, I want to find a way to Easter Egg that. :)
