### ISSUE TITLE
URL is double(?) escaped in Planner

### ISSUE THREAD

**Issue by aslakknutsen** [fabric8io/fabric8-ui#274]
http://prod-preview.openshift.io/aslak%404fs.no/Aslak-Test

Open up any Detail view of a WI and it works, url becomes: http://prod-preview.openshift.io/aslak%25404fs.no/Aslak-Test/plan/detail/2

Close the Details and try to open another:
Notification comes up: "/aslak%2525404fs.no/Aslak-Test/plan/detail/6 not found"
![screenshot from 2017-03-13 16-35-28](https://cloud.githubusercontent.com/assets/132158/23861707/26419318-080b-11e7-9c4b-b408ba0cea6b.png)

**Comment by pmuir** [comment]
Looks like a bug in planner where they call navigate which is re-encoding the URL. Will try to fix and submit PR.
