### ISSUE TITLE
Submenu vanishes when opening the detail view in Planner

### ISSUE THREAD

**Issue by michaelkleinhenz** [fabric8io/fabric8-ui#277]
Current prod version as of bug, Chrome Beta Current: when in Planner, opening the detail view of a work item from the list view removes the submenu bar from view, never to be seen again. Reload brings it back, though.

**Comment by pmuir** [comment]
@michaelkleinhenz please can you provide the version number from the footer. Something like: ` ( v1.6.1 Build#49 2017-03-13T02:44:11+00:00 )`

**Comment by pmuir** [comment]
Can't reproduce.
