### ISSUE TITLE
migrate fabric8-runtime-console's use of Caddy into fabric8-ui for proxying, serving content + templates

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-ui#300]
as discussed on chat yesterday we could either:

* migrate the [Caddyfile](https://github.com/fabric8-ui/fabric8-runtime-console/blob/master/Caddyfile) into the equivalent nginx thingy
* migrate fabric8-ui to just use Caddy instead of nginx (which is probably the simplest thing to do)

The main thing is we need possible proxying (if CORS doesn't work on OSO)
https://github.com/fabric8-ui/fabric8-runtime-console/blob/master/Caddyfile#L11-L18

Also we use templates in caddy:
https://github.com/fabric8-ui/fabric8-runtime-console/blob/master/Caddyfile#L10

to load a JSON template
https://github.com/fabric8-ui/fabric8-runtime-console/blob/master/src/config/oauth.json

which is populated from environment variables, defined via a [ConfigMap](
https://github.com/fabric8-ui/fabric8-runtime-console/blob/master/src/main/fabric8/cm.yml#L7) then exposed in a [Deployment](https://github.com/fabric8-ui/fabric8-runtime-console/blob/master/src/main/fabric8/deployment.yml#L10-L40) which we'll also need to migrate.

The configuration will change a bit mind you when we switch to ngx-login-client - we'll need to know the OSO API server URL (in the proxy config or in the client depending on if we need the CORS proxy or not) along with where to talk to the KeyCloak/almighty back end etc

**Comment by pmuir** [comment]
Status update: I started to impl in nginx, but realised that a module I need for nginx is not built as RPMs for CentOS so @mohammedzee1000 or @dharmit will build the right container with the module in for me in the next day or two. If we block on this in the meantime let me know, and I will just use caddy for now.

Regarding configuration: We currently inject the API URLs to use in to the code (as documented e.g. in ngx-login-client). I will work out a way to similarly inject them in to the nginx configuration from a yaml file.

**Comment by pmuir** [comment]
I guess I will template the nginx config file using some JS templating / yaml thingy.

**Comment by jstrachan** [comment]
@pmuir ah thanks! Just noodling that module now; will try update fabric8-runtime-console to use a similar approach too...

**Comment by pmuir** [comment]
it's the https://github.com/openresty/headers-more-nginx-module that I am missing on centos - it's in apt-get as nginx-extras if that helps anyone.

**Comment by pmuir** [comment]
Regarding proxying, the module is needed is being added to a container, I hope for an update tomorrow.

For dev proxying I suggest we just use the webpack dev server's inbuilt support for proxying and use the same config loader I wrote today to configure it. I can do that tomorrow if you agree @jstrachan

**Comment by jstrachan** [comment]
@pmuir sounds great to me yeah. In dev mode we can avoid templating too and just use the web pack env var stuff directly. Sounds like dev mode will be slicker and require less download/messing around which is a big win too ;)

I'm reasonably hopeful for fabric8-ui we can minimise templating at all too; its more for the fabric8-runtime-console side of the house. 

Many thanks!
