### ISSUE TITLE
Token remain in the URL after login.

### ISSUE THREAD

**Issue by vikram-raj** [fabric8io/fabric8-ui#310]
Token remain in the URL after login and it throws NavigationError when the user performs any activity on the page.

Video link for reference: https://youtu.be/Cjcu15xZrR0

**Comment by pmuir** [comment]
Reproduction: Navigate to http://prod-preview.openshift.io/rhn-support-pmuir/BalloonPopGame/plan when not logged in, click login, then click a work item.

I suspect this is caused by 274 which is fixed when we upgrade planner in platform. I will look again at that point.

**Comment by pmuir** [comment]
The upgrade to planner has made this worse, the navigation now no longer completes when you aren't logged in.
