### ISSUE TITLE
Initiate federated identity linking after successful login

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8io/fabric8-ui#322]
Backend now supports federated identity linking. See details here - https://github.com/almighty/almighty-core/pull/1015

Currently we hardcoded auto-linking during login. But here is proposed workflow:

- User logins using UI. UI calls `/api/login/authorize` with no parameters.
- `/api/login/authorize` logins the user and checks if there is any unlinked federated identities. If no, then adds `linked=false` parameter to the response Location header. If yes, then adds `linked=true`. Redirects back to origin referrer.
- UI checks the linked parameter and if it's set to false then warns the User that some additional authorization in github and OSO is needed
- UI initiates linking by calling:
**GET** `/api/login/link`
**Header**: `Authorization: Bearer <accessToken>`
**Optional parameter:** `redirect` - URL to be redirected to after successful account linking. If not set then will redirect to the referrer instead

As soon as this workflow is in place we will stop auto-link accounts during login.

**Comment by joshuawilson** [comment]
@dgutride can you take this on? If you need anyone else to help, let me know or just ask.

**Comment by pmuir** [comment]
Can we do this post-summit, the current workflow is fine I think.

**Comment by joshuawilson** [comment]
@alexeykazakov @dlabrecq can you please update this.

**Comment by alexeykazakov** [comment]
It has been implemented. So, closing it. If we have any issues with the current approach or if we want to improve it then let's open a new issue(s).
