### ISSUE TITLE
Navigation on mobile does not show all links

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8io/fabric8-ui#365]
The navigation on mobile devices (tested on Safari and Chrome, iOS) does not show all of the links. I can see the user dropdown, but the other items in the secondary navigation do not appear.

The menu should render in the same as the homepage (logged out).
<img width="357" alt="screen shot 2017-03-26 at 8 49 42 pm" src="https://cloud.githubusercontent.com/assets/4032718/24337003/c607a14e-1265-11e7-9d33-6e3df5218da3.png">

**Comment by joshuawilson** [comment]
@mindreeper2420 I'm giving this to you to include in your work to make the app mobile ready/viewable.

**Comment by mindreeper2420** [comment]
closed by PR #1566
