### ISSUE TITLE
Use conditional requests 

### ISSUE THREAD

**Issue by xcoulon** [fabric8io/fabric8-ui#370]
Support for conditional requests is landing on the platform: https://github.com/almighty/almighty-core/issues/965

But on the UI side, the browser does not include the `If-None-Match` or `If-Modified-Since` headers after the first request on an endpoint that returned an `ETag` or `Last-Modified` header, which means that the server will return the whole data again in subsequent requests.

Also, for responses that contain a `cache-control: max-age=...` header, the data should be kept in cache and no request should be submitted to the server until the data expired in the local (browser) cache.

**Comment by pmuir** [comment]
I can see cache-control working, I'm getting resources from the disk cache.

**Comment by pmuir** [comment]
I have checked this in Chrome where it doesn't send those headers, and in Firefox, where it does. 

I'm not sure how to stop chrome looking at the cache headers but keep looking at the etag headers.

**Comment by pmuir** [comment]
The cache headers are working fine, so I don't think this is urgent.

**Comment by pmuir** [comment]
This is working
