### ISSUE TITLE
Woopra action links are malformatted

### ISSUE THREAD

**Issue by qodfathr** [fabric8io/fabric8-ui#376]
Woopra links for actions are invalid. e.g. "/cctrieloff/_settings/tokens" is being logged with the following hyperlink "http://prod-preview.openshift.iohttp//prod-preview.openshift.io/cctrieloff/_settings/tokens"

**Comment by pmuir** [comment]
Appears to be a woopra error. I think it's fixed now. Please check it.

**Comment by qodfathr** [comment]
Agreed. Fixed.
