### ISSUE TITLE
Z index of Toast notifications is below the space wizard mal

### ISSUE THREAD

**Issue by pmuir** [fabric8io/fabric8-ui#391]

**Comment by dgutride** [comment]
![toast-notification](https://cloud.githubusercontent.com/assets/7306953/24511904/0b394556-153b-11e7-9b1e-8cb2ce681936.png)

@pmuir - can you be a bit more specific about what you'd like changed here?  It seems to be correct if I'm understanding the title of this issue correctly.

**Comment by pmuir** [comment]
That does look correct. Maybe it was if you click wizard? If you replay yesterdays integration demo, that's where I spotted it.

**Comment by joshuawilson** [comment]
it might be a browser issue, you should try Chrome and FF

**Comment by dgutride** [comment]
@pmuir - I reviewed the demo video and tried again on Chrome (which was the browser used in the demo) - this issue appears to have been addressed (both on prod-preview and locally when I run it).  Moving to closed...
