### ISSUE TITLE
Top nav broken (showing user nav) when editing a work item

### ISSUE THREAD

**Issue by pmuir** [fabric8io/fabric8-ui#393]

**Comment by dgutride** [comment]
![work-item](https://cloud.githubusercontent.com/assets/7306953/24511683/67754fc8-153a-11e7-8893-6360b09ad5ac.png)

@pmuir - this is what I'm seeing right now, it seems to be correct to me unless you are expecting something to change in this view?

**Comment by pmuir** [comment]
Can you double check this weeks demo video - Michael Virgil will have a link.
