### ISSUE TITLE
Get typeaheads working

### ISSUE THREAD

**Issue by pmuir** [fabric8io/fabric8-ui#41]
I was struggling to get both ng2-bootstrap and ng2-typeahead to work at all. Anyone want to take a look and put an example in?

**Comment by pmuir** [comment]
Couple of TODOs in the code for this.

**Comment by pmuir** [comment]
@mitchharpur can you look at this one?

**Comment by joshuawilson** [comment]
We do have type ahead in Planner that pulls the data from the backend. Where do you need them?

It really depends if you have a static list or a search of that large data set.

**Comment by pmuir** [comment]
I think there is one in team membership dialog, and there are a few filter boxes (e.g. in profile/spaces) that need them. Both will be searching the backend, not a static list, eventually. Right now it's a client side list obviously.

**Comment by pmuir** [comment]
one for ngx-widgets
