### ISSUE TITLE
jsonspi response will have type="users" for User API , instead of "identities"

### ISSUE THREAD

**Issue by sbose78** [fabric8io/fabric8-ui#413]

**Comment by pmuir** [comment]
I can probably pick this up. @sbose78 when does it switch over?

**Comment by sbose78** [comment]
@pmuir 
https://github.com/almighty/almighty-core/issues/1076 is still being worked upon by @xcoulon .
Should be switched over by Monday.

**Comment by pmuir** [comment]
PR created @sbose78 see linked commit. Please test
