### ISSUE TITLE
chunk.js not located in bundle.map on Edge

### ISSUE THREAD

**Issue by qodfathr** [fabric8io/fabric8-ui#438]
Noticed the following error when using Microsoft Edge:

Could not locate webpack:///_assets/lib/8.bd5af6514bafa822b6a0.chunk.js specified in source map http://prod-preview.openshift.io/_assets/lib/8.bd5af6514bafa822b6a0.bundle.map.

Not sure if that impacted anything, tho.

**Comment by pmuir** [comment]
I suspect this was a caching problem.

**Comment by joshuawilson** [comment]
This appears to no longer be an issue. I'm closing it for now, @qodfathr if you are still seeing this please reopen it.
