### ISSUE TITLE
Updation of user email will not work.

### ISSUE THREAD

**Issue by sbose78** [fabric8io/fabric8-ui#453]
This is a behaviour that would be caused when https://github.com/almighty/almighty-core/pull/1035 is merged. We are disabling the email updation till we figure out how to do the same properly on the keycloak side as well.

The API side fix would be made as part of :
 https://github.com/almighty/almighty-core/issues/1109

Only after that, 
email can be updated from the UI again.

CC: @alexeykazakov

**Comment by pmuir** [comment]
@dgutride can you look at this one?

**Comment by dgutride** [comment]
Fixed with https://github.com/fabric8io/fabric8-ui/pull/493 - @pmuir
