### ISSUE TITLE
Update to PatternFly 3.23.1

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8io/fabric8-ui#474]
In order to consume the latest PatternFly icons and components, PatternFly needs to be updated to the latest version. **NOTE: visual designs will not be a 1-1 to patterns until this is completed**

The correct version can be found here: https://github.com/patternfly/patternfly/releases/tag/v3.23.1

**Comment by joshuawilson** [comment]
I tried using this updated version of PF and it broke the UI.

**Comment by mindreeper2420** [comment]
@joshuawilson that probably happened due to a lot of custom code trying to replace the grid/column framework of PatternFly, as well as deviations from PatternFly patterns. This might be best done once the platform is returned to following the correct framework layout.

**Comment by joshuawilson** [comment]
@mindreeper2420 PRs are always welcome. :)

**Comment by mindreeper2420** [comment]
@joshuawilson - can I take out all of the custom flex bits and other deviations from PF? :) Returning it to the default PF would also allow a lot to work on mobile, without custom code ;-)

**Comment by joshuawilson** [comment]
I'm fine with that. You and @SMahil need to maintain it. If you can live with that way, works for me.

I had questioned the use of flexbox from the beginning as it is not a part of PF (yet).

**Comment by mindreeper2420** [comment]
I started to pull it out as I worked on various pages (and updated the navigation), so I have a path in mind to go back to the framework defaults. It will take time, but can definitely be done. I think it'd be a worthy chunk of effort (all dependant on deadlines) to include as an early piece to the next phase of work.

**Comment by mindreeper2420** [comment]
With all of the other fixes/priority items on the table, I don't see this as doable in a week. It will require a lot of line-by-line code review :-/ Give me a solid week of no other work, then I'd have a chance.

**Comment by joshuawilson** [comment]
Then I think we should save it for after May 1st

**Comment by mindreeper2420** [comment]
Works for me. I'll do some research on the next PF versions in the mean time to see if we might be able to provide some of the upcoming enhancements as a part 2 of returning this to base PF. I'll let you know what I find out.

**Comment by joshuawilson** [comment]
thanks

**Comment by mindreeper2420** [comment]
Closed by https://github.com/fabric8io/fabric8-ui/pull/1419
