### ISSUE TITLE
Also support GitHub browser URLs for code bases

### ISSUE THREAD

**Issue by qodfathr** [fabric8io/fabric8-ui#502]
Right now, using a GitHub "clone URL" works fine for adding a code base (e,g, https://github.com/qodfathr/helloworld-msa.git); however, it should also be possible to simply copy the URL out of the browser address bar (e.g. https://github.com/qodfathr/helloworld-msa). Today, if trying to add a code base with the browser URL, the response is "Invalid GitHub repository."

**Comment by dlabrecq** [comment]
Currently, the Add codebases panel supports 3 types.

1. HTTS URL: git@github.com:patternfly/patternfly.git
2. SSH URL: https://github.com/patternfly/patternfly.git
3. Full name: patternfly/patternfly

What is shown above is copied directly from the "Clone or download" button on GitHub. However, I can change that to accept an URL without .git at the end.

**Comment by dlabrecq** [comment]
Fixed. See https://github.com/fabric8io/fabric8-ui/pull/505
