### ISSUE TITLE
List all spaces

### ISSUE THREAD

**Issue by VineetReynolds** [fabric8io/fabric8-ui#53]
**Description**

As a owner or participant of spaces, I'd like to view a list of spaces I'm currently collaborating in,
so that I can view various activities in that space.

The spaces should be listed at the following route in the UI : `/<username>/spaces`

The list of spaces, that the user collaborates in, should be retrieved from the REST API from the Spaces resource at `/api/spaces`.

**Functional Acceptance criteria:**

1. The list of spaces should contain all private and public spaces that the specified user collaborates on
2. The description of the space should be provided to inform users about the nature of the space

~~3. Clicking on a space within the space list should open the space~~

**Tasks**

1. Create a ng SpaceService [#65]
2. Create a ng list service component [#66]

**Comment by pmuir** [comment]
Fixed by #269 I think
