### ISSUE TITLE
Cant associate GIT repo code base.

### ISSUE THREAD

**Issue by cctrieloff** [fabric8io/fabric8-ui#533]
Router Event: NavigationEnd
patternfly.css:2NavigationEnd(id: 45, url: '/cctrieloff/testv5/create/(action:add-codebase)', urlAfterRedirects: '/cctrieloff/testv5/create/(action:add-codebase)')
patternfly.css:2NavigationEnd
https://api.prod-preview.openshift.io/api/spaces/ddaa5594-b5e3-44a4-95c7-7665348de4ee/codebases Failed to load resource: the server responded with a status of 401 (Unauthorized)
main.8fe7ecd….bundle.js:1ResponseLogger.error @ main.8fe7ecd….bundle.js:1CodebasesService.handleError @ 0.0f7703c….chunk.js:1(anonymous function) @ 0.0f7703c….chunk.js:1CatchSubscriber.error @ patternfly.css:2Subscriber._error @ patternfly.css:2Subscriber.error @ patternfly.css:2a @ main.8fe7ecd….bundle.js:1ZoneDelegate.invokeTask @ polyfills.f49acb8….bundle.js:1onInvokeTask @ patternfly.css:2ZoneDelegate.invokeTask @ polyfills.f49acb8….bundle.js:1Zone.runTask @ polyfills.f49acb8….bundle.js:1ZoneTask.invoke @ polyfills.f49acb8….bundle.js:1
https://api.prod-preview.openshift.io/api/spaces/ddaa5594-b5e3-44a4-95c7-7665348de4ee/codebases Failed to load resource: the server responded with a status of 401 (Unauthorized)
main.8fe7ecd….bundle.js:1ResponseLogger.error @ main.8fe7ecd….bundle.js:1CodebasesService.handleError @ 0.0f7703c….chunk.js:1(anonymous function) @ 0.0f7703c….chunk.js:1CatchSubscriber.error @ patternfly.css:2Subscriber._error @ patternfly.css:2Subscriber.error @ patternfly.css:2a @ main.8fe7ecd….bundle.js:1ZoneDelegate.invokeTask @ polyfills.f49acb8….bundle.js:1onInvokeTask @ patternfly.css:2ZoneDelegate.invokeTask @ polyfills.f49acb8….bundle.js:1Zone.runTask @ polyfills.f49acb8….bundle.js:1ZoneTask.invoke @ polyfills.f49acb8….bundle.js:1
/sw.js:1 Service Worker termination by a timeout timer was canceled because DevTools is attached.
https://api.prod-preview.openshift.io/api/spaces/ddaa5594-b5e3-44a4-95c7-7665348de4ee/codebases Failed to load resource: the server responded with a status of 401 (Unauthorized)
main.8fe7ecd….bundle.js:1ResponseLogger.error @ main.8fe7ecd….bundle.js:1
https://api.prod-preview.openshift.io/api/spaces/ddaa5594-b5e3-44a4-95c7-7665348de4ee/codebases Failed to load resource: the server responded with a status of 401 (Unauthorized)
main.8fe7ecd….bundle.js:1ResponseLogger.error @ main.8fe7ecd….bundle.js:1
DevTools failed to parse SourceMap: https://prod-preview.openshift.io/_assets/lib/8.60bb00930a1c143a2a52.bundle.map

![screenshot from 2017-04-05 20 28 21](https://cloud.githubusercontent.com/assets/13753654/24734652/7fb29f2a-1a4c-11e7-8b95-77f0ba357b32.png)

**Comment by joshuawilson** [comment]
You can't assign repos when you aren't logged in.

**Comment by cctrieloff** [comment]
Ack, will check however maybe message should be, 'log-in' to add repos.

Carl.

**Comment by joshuawilson** [comment]
I agree, we have talked about doing that. 

I would prefer the github model of view without logging in and then be prompted for login when you want to do something that requires it. However this is not the current design and is outside of the scope of the demo. Hopefully, we can work with UX to come up with a flow that works like that soon.

**Comment by cctrieloff** [comment]
Ack, maybe for now (next week) we can just update the error message to be
useful to the user. i.e. 'Must be logged in to perform this action" as a
start.

Carl.

**Comment by pmuir** [comment]
We have a global action to update the ability to view screens when not logged in - #319
