### ISSUE TITLE
Update Navigation

### ISSUE THREAD

**Issue by joshuawilson** [fabric8io/fabric8-ui#540]
Update the navigation to match the design.

https://redhat.invisionapp.com/share/R2AWXA6DU#/screens/224263812

**Comment by pmuir** [comment]
@crobson is this ready for development yet?

**Comment by catrobson** [comment]
Let me make one update to the visual design document this morning to reduce confusion.  It will be ready in an hour or less.

**Comment by catrobson** [comment]
Visual designs finalized.  Ready for implementation:  https://redhat.invisionapp.com/share/N7B8IRLUK

**Comment by mindreeper2420** [comment]
@catrobson @joshuawilson as Brian and I did some preliminary work on this and he sent me the PSD file before he left, I can take this on.

**Comment by joshuawilson** [comment]
I'm good with that @mindreeper2420. When you get to routing changes, please let @pmuir and myself know. We can take care of that.
