### ISSUE TITLE
First log in flow

### ISSUE THREAD

**Issue by joshuawilson** [fabric8io/fabric8-ui#543]
This is what the user sees when they log into the system for the time. It uses the Profile page, but it is blank.

Here are the designs. 
https://redhat.invisionapp.com/share/TKB4AJP4M#/screens/226801770

This depends on #535

**Comment by catrobson** [comment]
Correct Wireframes to build from:  https://redhat.invisionapp.com/share/KQB6LEHM8

**Comment by dlabrecq** [comment]
Encountered problems with the login APIs and filed an issue here.

https://github.com/almighty/almighty-core/issues/1193

**Comment by dlabrecq** [comment]
Created the following PR:
https://github.com/fabric8io/fabric8-ui/pull/774

**Comment by dlabrecq** [comment]
The getting started page has gone through several iterations. I believe this can be closed now.
