### ISSUE TITLE
Codebases link on Analyze screen is malformed

### ISSUE THREAD

**Issue by qodfathr** [fabric8io/fabric8-ui#553]
![image](https://cloud.githubusercontent.com/assets/16322190/24767272/71670d9a-1acc-11e7-8cd9-97e4202e2ef5.png)

The link goes to: https://prod-preview.openshift.io/https///github.com/qodfathr/helloworld-msa

**Comment by pmuir** [comment]
@muruGanesan where was this link supposed to go?

**Comment by muruGanesan** [comment]
@Mgranfie , Hi Monica, could you please clarify the above point? 
I assume that, you would know about 'Codebase'.

**Comment by Mgranfie** [comment]
@muruGanesan @mindreeper2420 worked on this and can most likely assist.

**Comment by muruGanesan** [comment]
@Mgranfie thanks Monica

@pmuir, sorry! I have very limited knowledge on the "code base" workflow.

**Comment by muruGanesan** [comment]
@dlabrecq, Dear Dan, Could you please provide clarification on the above question? i.e. where these "Code base" links are pointed to?

**Comment by muruGanesan** [comment]
@pmuir, @qodfathr,  I got the clarity: 

1) Code base panel will show 'code base' links  i.e. links from Github repository of the logged in user -as shown in the picture. [**Assumption:** If an user got too many 'code' repository it will show most recent FIVE/TEN]
2) But, the link which Todd mentioned  "https://prod-preview.openshift.io/https///github.com/qodfathr/helloworld-msa" is WRONG URL  - it could be a bug in code.
3) I will check with Sukhvir  and fix this issue tomorrow.

**Comment by catrobson** [comment]
@mindreeper2420 - I think this is probably fixed, can you confirm and close?

**Comment by dlabrecq** [comment]
Fixed by https://github.com/fabric8io/fabric8-ui/pull/990
