### ISSUE TITLE
Codebases on Analyze screen should be a link

### ISSUE THREAD

**Issue by qodfathr** [fabric8io/fabric8-ui#554]
This:
![image](https://cloud.githubusercontent.com/assets/16322190/24767351/a6ec18f2-1acc-11e7-9307-8ad86ce2bb47.png)
should be a link to the Create/Codebases screen

**Comment by pmuir** [comment]
@fabric8-ux please review as that is a deviation from the design.

**Comment by catrobson** [comment]
@pmuir @qodfathr will be looking at how we have a standard "link to all" for widgets on the dashboard.

**Comment by catrobson** [comment]
Updated to have the title link.  Part of https://github.com/fabric8io/fabric8-ui/pull/818.  Closing this issue.
