### ISSUE TITLE
View/Add/Remove space collaborators

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8io/fabric8-ui#556]
Backend now suports space collaboration managment. See details here - https://github.com/almighty/almighty-core/pull/1116
We now can start using it in UI.

Part of https://github.com/almighty/almighty-core/issues/762 user story

**Comment by joshuawilson** [comment]
@dgutride can you take a look at this along with the work you are doing with Spaces?

**Comment by catrobson** [comment]
Wireframes being built for this by @muruGanesan

**Comment by muruGanesan** [comment]
Please look at the latest file URL:

https://redhat.invisionapp.com/d/#/console/10518262/228772655/comments/80395532

**Comment by joshuawilson** [comment]
moving it to Settings makes a lot more sense to me

**Comment by alexeykazakov** [comment]
This is done. Closing.
