### ISSUE TITLE
Search for a space in list of spaces

### ISSUE THREAD

**Issue by VineetReynolds** [fabric8io/fabric8-ui#56]
As a viewer or collaborator in spaces, I'd like to search the entire list of spaces I'm currently collaborating in, so that I can pinpoint a specific space to navigate to.

The spaces should be listed and searchable at the route: `/<username>/spaces`

The spaces should be retrieved from the REST API from the Spaces resource at `/api/spaces`.

**Functional Acceptance criteria:**

1. Entering a search criteria in the search box should initiate a search.
2. The spaces listed below in the space list, should match the search criteria.
3. The search criteria should be executed against the name of the space and the description.

**Tasks:**

1. Extend SpacesService to query the REST API with filter parameters. (#69)
2. Update SpacesComponent to use SpacesService for querying. (#70)

**Questions?**

1. Should the search results highlight the matches in the name and/or description.

**Comment by VineetReynolds** [comment]
For now, typeahead is likely to be used for implementing the search functionality.

**Comment by pmuir** [comment]
Fixed by #269 I think
