### ISSUE TITLE
Create a space

### ISSUE THREAD

**Issue by VineetReynolds** [fabric8io/fabric8-ui#57]
**Description**

As a project owner, I'd like to create a new space, so that I can collaborate with other team members on a specific project.

When creating a space, I should specify a name unique to the namespace where the space exists. Currently, this is the user account, and may eventually be an organization account.

**Functional Acceptance Criteria:**

1. Spaces can be created with an alphanumeric set of characters.
2. Space names should be unique to the entity where it is created - user or organization.
3. Spaces must have names. Blank space names are not permissible.
4. Spaces must have an associated process template at the time of creation - agile, scrum, etc.

**Tasks:**

1. Extend SpacesService to create spaces in the REST API backend. (#67)
2. Update SpacesDialogComponent to use SpacesService instead of DummyService to create spaces. (#68)

**Comment by pmuir** [comment]
@VineetReynolds the UI now has all of this.

**Comment by pmuir** [comment]
@VineetReynolds can you make sure you add validation to the rest endpoint for allowed chars. ^[a-zA-Z0-9_-]*$
