### ISSUE TITLE
Creating CodeBase - Failed to retrieve GitHub repo license

### ISSUE THREAD

**Issue by michaelvirgil** [fabric8io/fabric8-ui#573]
After creating a codebase from the UI and navigating to the Create -> Codebases tab, received the following error in the console when expanding the newly created workspace:

![screen shot 2017-04-07 at 11 12 51 am](https://cloud.githubusercontent.com/assets/11527926/24806703/b22e671c-1b83-11e7-8d0e-67d89a9d4867.png)

**Comment by dlabrecq** [comment]
That's expected when the repo doesn't have a license. I simply log a message and add "none" as the license value. We can hide the log message if that's causing confusion?

**Comment by michaelvirgil** [comment]
No problem, that explains it. Thanks.

**Comment by dlabrecq** [comment]
I'm going to silence the message and just set the value to none -- we don't really need a message in the console log. I'll mark this fixed when the PR is merged.

**Comment by dlabrecq** [comment]
Fixed by https://github.com/fabric8io/fabric8-ui/pull/583
