### ISSUE TITLE
Environments - no longer accessible (was just 1 hour earlier...)

### ISSUE THREAD

**Issue by michaelvirgil** [fabric8io/fabric8-ui#578]
After working with KB and Aslak to setting up and re-establishing my OSO account and syncing with KeyCloak - the pipelines for the newly create Space was successfully displayed. After logging off and retrying the integration script, the environments no longer come up in the UI... approximately an hour had passed.

![screen shot 2017-04-07 at 11 23 48 am](https://cloud.githubusercontent.com/assets/11527926/24807232/6ef3b798-1b85-11e7-8205-b7aefe13b4d6.png)

**Comment by michaelvirgil** [comment]
Update; After logging off and retrying the integration script, the environments now come up - other errors... 

- Error retrieving list ConfigMaps: Response with status: 403 Forbidden
- failed: Error during WebSocket handshake: Unexpected response code: 403

![screen shot 2017-04-07 at 11 50 16 am](https://cloud.githubusercontent.com/assets/11527926/24808179/d939e16a-1b88-11e7-9c1a-b4c32d2c6f0c.png)

**Comment by pmuir** [comment]
Environments are a tad broken right now for me too. We need to look at it.

**Comment by pmuir** [comment]
Looks like the upgrade to the tree list component broke this somehow. As this is a temp component until we move to the list view I'm reluctant to spend time on this. Will talk with Dan in the platform meeting later.

**Comment by joshuawilson** [comment]
fyi @dlabrecq

**Comment by dlabrecq** [comment]
I've been encountering the same token errors while testing the codebases page. Aslak had me log out and clear my cache and the problem cleared up. Although, this didn't have anything to do with the tree list component.

**Comment by dlabrecq** [comment]
I'm seeing the same Websocket error message, but no tree list errors

GET http://localhost:3000/_p/oso/api/v1/namespaces/default/configmaps 403 (Forbidden)

WebSocket connection to 'wss://api.free-int.openshift.com/api/v1/namespaces/default/configmaps?watch=true&access_token=Tf8EEERVlcfqn-y5dnQRHphKXU4AsIHGsMfi81Q_uqU' failed: Error during WebSocket handshake: Unexpected response code: 403

**Comment by jstrachan** [comment]
master should now have the environments page back without the`... /namespace/default/..` issue

**Comment by joshuawilson** [comment]
@michaelvirgil the Environments page has gone through some changes. Can you please verify this issue?

**Comment by joshuawilson** [comment]
They work now.
