### ISSUE TITLE
Codebase 'undefined' created

### ISSUE THREAD

**Issue by aslakknutsen** [fabric8io/fabric8-ui#579]
When you add a new codebase the popup notification contains "Codebase 'undefined' created".

**Comment by dlabrecq** [comment]
Fixed.

**Comment by aslakknutsen** [comment]
@dlabrecq I guess I'll take your word for it.. ;)

**Comment by dlabrecq** [comment]
Fixed by https://github.com/fabric8io/fabric8-ui/pull/583

**Comment by pmuir** [comment]
Dupe of #517
