### ISSUE TITLE
Wizard should use PF color variables. 

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8io/fabric8-ui#588]
The Wizard modal uses hex codes for close (border, alerts, etc) and should use PatternFly controlled colors instead for consistency and uniformity.

**Comment by pmuir** [comment]
TBH The whole wizard needs implementing inside the PF Wizard component (which is not yet built).

**Comment by joshuawilson** [comment]
Related to: https://github.com/fabric8-ui/ngx-widgets/issues/46

**Comment by joshuawilson** [comment]
@mindreeper2420 I'm going to guess that this will get fixed in the LESS conversion.
