### ISSUE TITLE
414 URI Too long on woopra calls

### ISSUE THREAD

**Issue by aslakknutsen** [fabric8io/fabric8-ui#593]
Seems all calls, even on subpages where referrer technically shouldn't contain the Token, to woopra somehow contain the token.

Could be history URL API is not called on inpage url change?

**Comment by pmuir** [comment]
I'm pretty sure it's called, as that is how angular is manipulating the URL. The key to this is to get the referrer changed I think.

**Comment by pmuir** [comment]
@aslakknutsen going to need a video or a reproduction instruction, as I don't see this trying either way of logging in.

**Comment by aslakknutsen** [comment]
Seems to be gone after cleaning Local Storage
