### ISSUE TITLE
User context menu show up hidden behind WorkItem details panel when active

### ISSUE THREAD

**Issue by aslakknutsen** [fabric8io/fabric8-ui#595]
![screenshot from 2017-04-10 13-16-24](https://cloud.githubusercontent.com/assets/132158/24859246/064745a8-1df0-11e7-8841-c9f4b0a42aca.png)

**Comment by pmuir** [comment]
See also #508 - I think we need a global guide for z-index.

**Comment by mindreeper2420** [comment]
The z-index can actually be lowered a lot - it is currently at 1050. That will fix the layering problem. Elements should only go up by 5-10 layers at a time.

**Comment by mindreeper2420** [comment]
PR https://github.com/fabric8io/fabric8-planner/pull/1562 fixes this issue

**Comment by joshuawilson** [comment]
thanks
