### ISSUE TITLE
GitHub repo api calls should be authenticated

### ISSUE THREAD

**Issue by qodfathr** [fabric8io/fabric8-ui#600]
When going to Codebases screen, getting error: 'Failed to retrieve GitHub repo: https://github.com/pmuir-demo-3/fri0704171413.git'

Root cause seems to be unauthenticated calls to api.github.com

"https://developer.github.com/v3/#rate-limiting"
message
:
"API rate limit exceeded for 'ip-addr'. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"

URL seems to be: https://api.github.com/repos/pmuir-demo-3/fri0704171413

**Comment by corinnekrych** [comment]
@pmuir @joshuawilson the 60 requests an hour is fixed by adding Authorisation to Headers in this PR:
https://github.com/fabric8io/fabric8-ui/pull/616
according to the doc the limit is now 5000 requests an hour.
Let's close this issue.
