### ISSUE TITLE
Put work item type in details

### ISSUE THREAD

**Issue by qodfathr** [fabric8io/fabric8-ui#603]
When I open the work item details, it would be helpful to see the name of the type, rather than just the icon.

![image](https://cloud.githubusercontent.com/assets/16322190/24874240/ff31905a-1df1-11e7-8e1c-0292e914efae.png)

It's very hard for me to know what type 459 is in the above example.

**Comment by mindreeper2420** [comment]
This should be updated in the visual design holistic view as well. @catrobson

**Comment by joshuawilson** [comment]
@mindreeper2420 can you do this or pass it to @SMahil once the designs are done, since this will be fixed in the Planner.

**Comment by catrobson** [comment]
Can you assign this to me?  I'll update and get to @SMahil

**Comment by joshuawilson** [comment]
This has been fixed.
