### ISSUE TITLE
Making a WI a child leaves it in both child and non-child state

### ISSUE THREAD

**Issue by qodfathr** [fabric8io/fabric8-ui#604]
![image](https://cloud.githubusercontent.com/assets/16322190/24874490/d8a5e0b6-1df2-11e7-8b01-7e3640e38b5b.png)
I thought I was making 460 a child of 459, but maybe I got that backwards. Regardless, now 459 is showing as both a child and not a child.

**Comment by joshuawilson** [comment]
@michaelkleinhenz can you review this and duplicate it in Planner unless it is really something that goes to the tree-list component, then it should go to Widgets @dlabrecq

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-planner#2007
