### ISSUE TITLE
prod-preview.openshift.io isn't loading (except incognito) 

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-ui#609]
prod-preview.openshift.io isn't loading  (except incognito) 

Gist link : https://gist.github.com/naina-verma/2fe9df96fc9a5f9109b854d5b9ecadd4
![bug](https://cloud.githubusercontent.com/assets/19172870/24894454/178ce3c8-1ea8-11e7-8c78-b17244e8740e.png)

**Comment by joshuawilson** [comment]
Looks fine to me. Did you try to clean the local storage and refresh?

**Comment by maxandersen** [comment]
I saw this today too - had to clean the local storage and refresh.

But why is this required ? seems to happen when we done an update - we can't expect users to know how to go clean local storage.

**Comment by joshuawilson** [comment]
We already have 2 issues tracking the need to fix the logout, #260 and #594, going to close this a duplicate. 

@maxandersen to answer your question is has to do with token timeouts and when they expire or don't. Without a functional logout, we can't now clear the tokens. So you must do it manually.
