### ISSUE TITLE
prod-preview.openshift.io is not redirecting directly to home page after auth

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-ui#611]
prod-preview.openshift.io is not redirecting directly to home page after auth
Steps to reproduce
- Authenticate with RH credential (incognito tab)
- after auth it  will not directly land on home page
 
Video Link :https://drive.google.com/a/redhat.com/file/d/0B1qUq_laG6COckFoTWNFVFZkYms/view?usp=sharing
![screenshot from 2017-04-11 11-54-57](https://cloud.githubusercontent.com/assets/19172870/24895406/d8265e5c-1ead-11e7-8af3-cd05b8de46ef.png)

**Comment by joshuawilson** [comment]
@naina-verma what does it do if it doesn't redirect to home? I have noticed a delay and filed an issue for it, is that what you are referring to?

**Comment by joshuawilson** [comment]
This does not appear to be an issue any more.
