### ISSUE TITLE
Add 'company' field in UI , on the User Profile page

### ISSUE THREAD

**Issue by sbose78** [fabric8io/fabric8-ui#612]
related to the task created by @pmuir : 
https://github.com/almighty/almighty-core/issues/1052

**Comment by pmuir** [comment]
And also add to the analytics service - https://github.com/fabric8io/fabric8-ui/blob/master/src/app/shared/analytics.service.ts#L170 add a new trait called 'company'

**Comment by joshuawilson** [comment]
This is related to #358

**Comment by dlabrecq** [comment]
Added to update profile page. See https://github.com/fabric8io/fabric8-ui/pull/1263.

Will update profile page, next.

**Comment by dlabrecq** [comment]
The latest profile page is available in prod.
