### ISSUE TITLE
Add Pull request builder

### ISSUE THREAD

**Issue by pmuir** [fabric8io/fabric8-ui#63]
When someone submits a PR, have ci.centos.org build a copy of the app, and serve it up from a unique URL, so the reviewer can use the changed system without having to do local work.

**Comment by joshuawilson** [comment]
@rawlingsj you did something like this for the runtime-console. Can you do it for Planner too?

**Comment by rawlingsj** [comment]
Yeah we have that in the runtime console using a Jenkins pipeline.  I can refactor the code to its just one or two lines in a Jenkinsfile that does this https://github.com/fabric8-ui/fabric8-runtime-console/blob/master/Jenkinsfile#L66

I'll make a PR and you can test it out.

**Comment by joshuawilson** [comment]
Thanks.

**Comment by joshuawilson** [comment]
This has been done for all the UI repos. Closing.
