### ISSUE TITLE
forge obsidian/launchpad wizard should default the the `labelSpace` property name from the current space  

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-ui#640]
if we use the UI to create a space called `foo` then the wizard appears for quickstarts etc; when we start to invoke the forge wizard we should pass in the property value `labelSpace = "foo"` (and maybe hide the labelSpace field in the UI if folks hit `Next` to the namespaces page) so that we can pass the current 'labelSpace' into the back end to do the right thing from a labelling perspective. 

Then the created `BuildConfig` will have a label of `space: foo` added to it when the `Finish` button is pressed - which will allow folks to filter Pipelines via space etc

**Comment by mitchharpur** [comment]
This should now be corrected. The field is also now readonly
