### ISSUE TITLE
forge wizard seems to forget the `project name` you enter if you hit Next to go to next pages

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-ui#699]
usually you get a failure at the `Finish` point as it tries to create a git repo called 'demo' - despite what you typed on the first page

**Comment by jstrachan** [comment]
I think this is mostly fixed now?

**Comment by mitchharpur** [comment]
this should now be corrected. On every page when the next buttons  ... all the fields are posted to the api
