### ISSUE TITLE
fabric8 create project UI

### ISSUE THREAD

**Issue by rawlingsj** [fabric8io/fabric8-ui#7]
fabric8 has a create new project UI:

<img width="1439" alt="screenshot 2016-12-07 10 47 16" src="https://cloud.githubusercontent.com/assets/1457180/20964753/b6f455b8-bc6a-11e6-9c79-294757370f36.png">

Which is a front end to [fabric8-forge](https://github.com/fabric8io/fabric8-forge) a set of forge addons that can be used with the (currently at) 48 https://github.com/fabric8-quickstarts to generate new projects.  

To avoid duplication of work across projects it would be good to get a handle of what work is required going forward as there are a few other efforts that have doing something similar.  

I'm sure it's more detailed but at a super high level what's needed here?

- migrate existing forge UI from fabric8-console to angular 2 
- unify 
   - https://github.com/fabric8io/fabric8-console
   - https://github.com/obsidian-toaster/generator-frontend
   - https://github.com/almighty/almighty-ui
- are there forge addons from obsidian-toaster and the previous almighty project that need to be moved to fabric8's github org and included in fabric8-forge?

This is just a start  - lets flesh out or correct where we can

/CC @jstrachan @rajdavies @cmoulliard @pmuir

**Comment by jstrachan** [comment]
@gashcrumb has a port to angular2 of the fabric8 forge UI

**Comment by gashcrumb** [comment]
Yep, right now it's hiding out here -> https://github.com/redhat-ipaas/ipaas-api/tree/master/sandbox

**Comment by cmoulliard** [comment]
Obsidian is also angular2 + patternfly 

Here is the code generator front where we have published it today (backend should be redeployed to generate a zip file - will be affective in 1H)

Demo : https://obsidian-toaster.github.io/intro

Projects :  
Front :  https://github.com/obsidian-toaster/generator-frontend
Forge Backend :  https://github.com/obsidian-toaster/generator-backend

**Comment by rawlingsj** [comment]
@cmoulliard is the Obsidian frontend still WIP?  Is it worth Obsidian switching and collaborating on the fabric8 one which has been around for over a year?  We can then all work together to fill in the missing parts because unless I'm missing something they seem to do the same thing?

Yes the fabric8 forge UI needs to be angular 2 but as @gashcrumb mentioned that work has already started.

**Comment by jstrachan** [comment]
@gashcrumb has migrated the forge part of fabric8 console to angular 2 already - its being used in the iPaaS https://github.com/redhat-ipaas/ipaas-api/tree/master/sandbox

at some point it'd be good to move all of [fabric8-console](https://github.com/fabric8io/fabric8-console) over to angular2. I think @joshuawilson is looking at supporting angular 1 and 2 together for a little while tactically until we can migrate everything over

**Comment by cmoulliard** [comment]
@rawlingsj For sure James. We will Almighty + Obsidian + Fabric8 collaborate together to design the new Developer UI Experience. The ideas of the different groups/teams will be discussed in order to design/develop the different screens/wizards/workflows.

The Obsidian Front end like the Fabric8 front end will be merged at some point as we are developing our respective projects using the same standards; Angular2 + PatternFly & REST Forge endpoints

**Comment by jstrachan** [comment]
@cmoulliard this repository is the UI created as part of Dev Experience &  the fabric8 team and anyone else who wants to contribute and its being created from the fabric8 console. Anything anyone has outside of the fabric8 console should be merged in.

**Comment by jstrachan** [comment]
@cmoulliard you might want to integrate any Obsidian Forge addons into the [fabric8-forge](https://github.com/fabric8io/fabric8-forge) project so that they show up in the fabric8 console (and hence in the DevExp console)

**Comment by pmuir** [comment]
@jstrachan +1 - this is our integration repository now.

**Comment by cmoulliard** [comment]
As we are preparing a first release of Obsidian - TP in 2 weeks to support Eclipse Vert.x, Spring Boot + Apache Tomcat with the Front Generator tool, I suggest that we discuss/start this merging process  beginning of next year in order to : 
- Move our Quickstarts to Fabric8 quickstarts organization
- Merge code developed for the new addon used by the Front in order to create a Vert.x/Swarm or SpringBoot project
- Integrate development done for Front end of Obsidian

**Comment by jstrachan** [comment]
@cmoulliard BTW the fabric8 console has had wizards to create projects in vertx, spring boot, tomcat, karaf & WF Swarm using jboss forge for over a year ;)

**Comment by cmoulliard** [comment]
As the purpose of this ticket is to discuss "Create Project UI", we should keep the discussion around this topic ;-)

**Comment by jimmidyson** [comment]
@cmoulliard Out of interest, why are you creating something that has existed in fabric8 console for a long time? Why not just reuse those or if they aren't quite what you want, help to update them?

**Comment by gastaldi** [comment]
Just a minor consideration here: https://github.com/fabric8io/fabric8-forge/issues/726 decouples the Forge integration (moves a subset of the Fabric8-forge-core  classes needed for integration with the Forge UI API) from the Fabric8-forge-core and it's maintained by the Forge team (me), so it's updated everytime a Forge release happens.

**Comment by cmoulliard** [comment]
The workflow requested by the PM was different from what has been created in Fabric8

- From vert.x/spring boot (and later wildfly swarm) --> create a zipped file
- From vert.x/spring boot (with or without Red Hat SSO) --> create a zipped file

and the frontend designed using angular2, patternfly & almighty

**Comment by jstrachan** [comment]
@cmoulliard I don't grok the 'create zipped file' comments above. If you'd rather create projects as downloadable tarballs and have no git, CI, CD, OpenShift integration, that could be added as a separate wizard step (to avoid the git + CD and just make a tarball). It doesn't sound terribly useful though does it? :) Most folks wanna build + run projects really

**Comment by jstrachan** [comment]
Oh you mean you want a stand alone start.spring.io style website only - and not have any OpenShift / CI / CD / git integration right? At least you can reuse the same underlying forge commands & may be able to repurpose most of the angular front end - its just a different action at the end (import to git + setup CD versus download tarball)

**Comment by gastaldi** [comment]
@jstrachan exactly, that's what the current backend is doing right now. We are reusing the Fabric8 addons, so it's basically the same thing

**Comment by rawlingsj** [comment]
so could we:

- add the obsidian quickstarts to fabric8 
- add the obsidian addons to fabric8-forge 
- add any missing UI bits to fabric8-console

Then Obsidian could just use fabric8?

Once we get this repo updated with the migrated angular 2 fabric8 forge UI (or the tactical option mentioned above) you'd satisfy the PM requirements, we'd avoid duplication and both projects would benefit from each other.

Would that work?

**Comment by gastaldi** [comment]
@rawlingsj that would be my thought as well, to happen after this first release

**Comment by jclingan** [comment]
I need to look at the Fabric8 create project UI. We don't want to duplicate work, but we also do not plan to support all the fabric8 features up front.

Post-December, we may have the opportunity to switch from "download zip" to a more online-centric experience since our target deployment focus is switching from the OpenShift Container Platform to OpenShift Online.

I dunno about others, but I could use a quick demo of the fabric8 create project UI. Recording already exist somewhere?

**Comment by edewit** [comment]
@jclingan this one is good: https://youtu.be/bERRJksRB1A?t=1012

**Comment by rawlingsj** [comment]
> this one is good: https://youtu.be/bERRJksRB1A?t=1012

yeah that's probably the best one we have 

FWIW you can find all the fabric8 demos here https://blog.fabric8.io/

If you don't want to support all the fabric8 features from day one then that's totally fine.  We could look adding feature flags for example but for me the main thing would be to reuse and extend what's already been developed in the community.

**Comment by jstrachan** [comment]
@jclingan yeah the above demo is probably the best. If you're super pushed for time here's a 6 minute video from about 6 months ago; the console's a little older but its about the same as today https://vimeo.com/170830750

BTW once a project is created via the web UI & the Forge wizards; we could easily configure what happens next via, say, a configuration (whether we want to download a ZIP or create a project in git & setup a CD Pipeline) - its easy to support either. Or we could make it a wizard page as to whether to import into git or download as a zip so the user can choose.

When inside OpenShift it makes more sense to spin up the project in a git repo and setup a CD Pipeline and build, test & run it. When running as a hosted public website, trying to do a start.spring.io type of site - then downloading a zip sounds fine; but the build, test and run approach is more appealing to developers really

**Comment by jclingan** [comment]
BTW, this is seriously great stuff! I watched the whole video last week, didn't realize that this is the same UI we are talking about here (versus prior versions). All goodness.

I'm going to take some of this offline since it relates specifically to product.

**Comment by joshuawilson** [comment]
Since we have an App Wizard in OSIO that talks to forge and generates projects and pipelines now, I'm closing this.
