### ISSUE TITLE
real time updates of pipelines seem to be broke in fabric8-ui

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/fabric8-ui#721]
so you have to keep hitting refresh to see a pipeline move through stages to completion

**Comment by jstrachan** [comment]
@pmuir any idea on this one? is it related to updates in how the observables are working?

**Comment by pmuir** [comment]
This was working fine as long the websockets connected as recently as Weds.

**Comment by jstrachan** [comment]
seems fine now!
