### ISSUE TITLE
Upgrade Font Awesome to 4.7.0

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8io/fabric8-ui#736]
In order to consume the full set of Font Awesome icons, we need to update to the latest 4.7.0 (we are currently using 4.6.3). This update gives us 41 new icons.

In order to make upgrades easier, we should separate Font Awesome from the PatternFly-Sass-CSS consumable and have it as a separate package in the package.json for each repo. Webpack will need to be configured to place the stylesheets in the correct location.

**Comment by joshuawilson** [comment]
@mindreeper2420 has this been done yet?

**Comment by mindreeper2420** [comment]
@joshuawilson no - this will be done as part of the Less conversion (the latest version of PatternFly uses the latest version of Font Awesome).

**Comment by mindreeper2420** [comment]
@joshuawilson this has been completed as part of PR #1419. The latest PatternFly version utilizes Font Awesome 4.7.0.
