### ISSUE TITLE
Move profile page into user dropdown; remove navigation

### ISSUE THREAD

**Issue by catrobson** [fabric8io/fabric8-ui#739]
To navigate to the profile page, I should click my username and select "My Profile".  At that point, my username should show as highlighted while showing the profile page.

![image](https://cloud.githubusercontent.com/assets/3739227/25016521/596ed1a0-204e-11e7-9c71-8cc404295981.png)

Wireframe showing this state: 
https://redhat.invisionapp.com/share/X7BA3VAMB#/224263817_Navigation_Space_Profile

If I look at another user, they would show up in the space/user dropdown, with no navigation to the right.

Wireframe showing this state:
https://redhat.invisionapp.com/share/X7BA3VAMB#/227842569_Navigation_View_Another_User

**Comment by joshuawilson** [comment]
I think this touches the work that both @dgutride and @dlabrecq. Can you both sort out who is going to change what?

**Comment by joshuawilson** [comment]
This is done.
