### ISSUE TITLE
Change "Sign in with GitHub" button to "Sign in with Red Hat Developers"

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8io/fabric8-ui#75]
We switched to keycloak authentication instead of github in almighty-core. Our keycloak uses developers.redhat.com as Identity Provider. We now should change the label/image of the sign-in button.

Related to https://github.com/fabric8io/fabric8-planner/issues/780 and https://github.com/almighty/almighty-core/pull/654

**Comment by pmuir** [comment]
Done with switch to new landing page.
