### ISSUE TITLE
On prod-preview.openshift.io, home page 'create a space' options are not operational

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-ui#758]
Workaround - Spaces can be created through the logged in user's profile.

Clicking on the 'create a space' options on the home page does nothing.

Originally mis-logged as:  
https://github.com/openshiftio/www.openshift.io/issues/84

**Comment by joshuawilson** [comment]
How do I reproduce this. It appears to work. There is an issue with using the Quickstarts but that is not required for creating a space.

**Comment by ldimaggi** [comment]
Resolved as of April 27
