### ISSUE TITLE
Enhancement request - to facilitate automated UI creation - add unique (within each page) ID's to UI elements 

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-ui#761]
The UI at present is difficult to work with for automated test creation - multiple elements share the same ID, path, selectors - for example:

![screenshot 63](https://cloud.githubusercontent.com/assets/642621/24676288/64cd2308-1950-11e7-9be5-7417513e20c8.png)

**Comment by joshuawilson** [comment]
@ldimaggi since only the tests will use the IDs you should be able to add them without breaking anything. Though I suggest you use [the component name - whatever the thing is].
