### ISSUE TITLE
Add lookupSpace(name: string) to SpaceService

### ISSUE THREAD

**Issue by pmuir** [fabric8io/fabric8-ui#82]
This is needed for us to e.g. load a context

**Comment by pmuir** [comment]
@VineetReynolds please can you do this.

**Comment by VineetReynolds** [comment]
@pmuir Yes, please assign it to me. I've already implemented it locally, and should have this ready very soon.

**Comment by pmuir** [comment]
@VineetReynolds I can't assign to you, I think you need to accept the collaboration invitation.
