### ISSUE TITLE
User dropdown should be full width

### ISSUE THREAD

**Issue by catrobson** [fabric8io/fabric8-ui#825]
The right hand dropdown under the user also be the full width of the name above it to be consistent with the left hand dropdown behavior.  Also not sure if we can get rid of the little gap between the primary nav and the dropdown itself, and "dock" it off of the navigation like the left hand dropdown is.

![image](https://cloud.githubusercontent.com/assets/3739227/25153947/80ad0130-245c-11e7-9bc5-e6a573314d60.png)

**Comment by mindreeper2420** [comment]
verified as fixed in Build 448 (June 15, 2017).
