### ISSUE TITLE
Status dropdown - make placeholder all green

### ISSUE THREAD

**Issue by catrobson** [fabric8io/fabric8-ui#826]
The status dropdown is a placeholder for now.  Please make it all green & OK looking for now until we have it functional.

![image](https://cloud.githubusercontent.com/assets/3739227/25154396/80cc202c-245e-11e7-87ce-53603401c52f.png)

**Comment by mindreeper2420** [comment]
PR filed: https://github.com/fabric8io/fabric8-ui/pull/829

**Comment by mindreeper2420** [comment]
<img width="263" alt="screen shot 2017-04-18 at 7 37 10 pm" src="https://cloud.githubusercontent.com/assets/4032718/25157307/78ba95ca-246e-11e7-968a-08f6649e8e87.png">
