### ISSUE TITLE
Refresh token every 10 minutes 

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8io/fabric8-ui#828]
Currently our tokens have pretty long lifespan - 24 hours. But the tokens will include the set of spaces available to the user. If this list is updated after the token was issued we will need to call SSO to verify permissions. So, if we refresh the token every 10 minutes or so we will minimize our calls to SSO.

**Comment by joshuawilson** [comment]
@alexeykazakov what needs to be done in the UI, change the refresh to 10 minutes?

**Comment by alexeykazakov** [comment]
@joshuawilson yes.

**Comment by joshuawilson** [comment]
@dgutride has this been done?

**Comment by dgutride** [comment]
@joshuawilson - this work was completed before summit - moving to closed
