### ISSUE TITLE
On https://prod-preview.openshift.io/ - user profile includes canned information

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-ui#859]
See attached screenshot:
![screenshot from 2017-04-19 09-07-21](https://cloud.githubusercontent.com/assets/642621/25181711/61574cda-24e0-11e7-8ca1-6677a436922e.png)

**Comment by mindreeper2420** [comment]
this is on purpose - there is no information for Activity at this time.

**Comment by joshuawilson** [comment]
@mindreeper2420 can you check with @catrobson and confirm what gets fixed vs what gets removed. And then remove the bits that go away.

**Comment by mindreeper2420** [comment]
@joshuawilson we're getting a list of pages that are going to be shown at demo and then remove static content from those screens. Pages that will not be shown will be left with static info, unless time allows to remove it.

**Comment by joshuawilson** [comment]
ok, thanks

**Comment by ldimaggi** [comment]
Closing - this is no longer an issue.
