### ISSUE TITLE
space.path is not set when fetching space from backend

### ISSUE THREAD

**Issue by pmuir** [fabric8io/fabric8-ui#86]
* **I'm submitting a ...**
[ x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**
The path of every space on http://fabric8.almighty.io/pmuir/spaces is 'undefined'

* **What is the expected behavior?**
The path is the name of the space, converted to a URL (i.e. spaces etc. removed)

**Comment by pmuir** [comment]
@VineetReynolds ^^^

**Comment by pmuir** [comment]
@VineetReynolds is going to remove space.path

**Comment by joshuawilson** [comment]
I think this is fixed.
