### ISSUE TITLE
On https://prod-preview.openshift.io/ - multiple edit user profile options all link to email field

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-ui#860]
See attached screenshot - trying to edit the bio or URL result in the email field being highlighted:

![screenshot from 2017-04-19 09-16-01](https://cloud.githubusercontent.com/assets/642621/25181996/40e351f0-24e1-11e7-894f-740a332cefd5.png)

**Comment by dlabrecq** [comment]
This was intentional as this page has not been fully implemented.

Fix by https://github.com/fabric8io/fabric8-ui/pull/1263

**Comment by dlabrecq** [comment]
As of today, the latest profile page is available in prod.
