### ISSUE TITLE
Create Space Wizard Modal inside of Create Space Wizard Modal

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8io/fabric8-ui#861]
On prod-preview, the Create Space wizard modal is appearing inside of another Create Space wizard modal when launching the wizard from prod-preview/USERNAME/_space. 

![screen shot 2017-04-19 at 9 53 51 am](https://cloud.githubusercontent.com/assets/4032718/25183716/5fa50e6c-24e6-11e7-9351-07a2421b5228.png)

**Comment by mitchharpur** [comment]
not reproducable ... issue is no longer occurring or might have been another side affect
