### ISSUE TITLE
Viewing pipeline history sets active navigation tab to Codebases

### ISSUE THREAD

**Issue by qodfathr** [fabric8io/fabric8-ui#870]
Create | Piplines | View Pipeline Runs for some pipeline

Notice that active 2nd level tab has changed from Pipelines to Codebases:

![image](https://cloud.githubusercontent.com/assets/16322190/25186073/0beb5f0e-24ed-11e7-9d0f-5aa8a6e81f26.png)

**Comment by joshuawilson** [comment]
The Pipelines tab should still be highlighted.
