### ISSUE TITLE
login with user A, logout, then login with user B result in "already logged in" error and stuck

### ISSUE THREAD

**Issue by maxandersen** [fabric8io/fabric8-ui#886]
login with user A, logout, then login with user B result in "already logged in" error and stuck.

And by stuck is meant most attempt after that to login result in being logged in as user A even though already supposedly logged out.

via tracing was found that no actual call is made to backend for doing logout.

**Comment by ldimaggi** [comment]
I saw the same behavior today while trying to create multiple automated tests - "logout" is not logging out the user.

**Comment by dgutride** [comment]
@alexeykazakov 
I think we might have the browser caching the redirect locally so it doesn't process
http://stackoverflow.com/questions/9020162/avoiding-301-redirect-caching - can we add a no-cache header to that api?
http://bugsquash.blogspot.com/2008/12/google-chrome-caches-301-redirects.html

**Comment by joshuawilson** [comment]
That is worth a try.

**Comment by alexeykazakov** [comment]
@dgutride I created an issue for core - https://github.com/almighty/almighty-core/issues/1227

**Comment by joshuawilson** [comment]
This has been fixed for a while. Closing.
