### ISSUE TITLE
About Modal Is Incorrect

### ISSUE THREAD

**Issue by mindreeper2420** [fabric8io/fabric8-ui#889]
The About Modal does not follow the designs, as given in Issue https://github.com/fabric8io/fabric8-ui/issues/740. Initial work merged with PR https://github.com/fabric8io/fabric8-ui/pull/852.

Requirements:
- footer needs to be removed from the site
- build and timestamp information should still be available
- overall implementation should match the [visual design](https://redhat.invisionapp.com/share/DCBC8D2RX#/229470358_Artboard_1)

Verification Conditions:
- review with UX (Jessica, Adam or Catherine)

**Current Implementation:**
![screen shot 2017-04-19 at 3 26 52 pm](https://cloud.githubusercontent.com/assets/4032718/25204897/b217ee02-252d-11e7-9758-ea4ab597a576.png)

**Design:**
![screen shot 2017-04-19 at 3 26 58 pm](https://cloud.githubusercontent.com/assets/4032718/25204899/b4700acc-252d-11e7-816f-ba3a683ee82b.png)

**Comment by joshuawilson** [comment]
I didn't want the footer removed until we verified the data in prod. Now that it is done that can be removed. 
The data does not display when you run it locally. You would need to run the prod build locally to see it. 
The styles do need to be updated. But we are moving incrementally. But this is a good reminder to keep moving forward.

**Comment by mindreeper2420** [comment]
Here is a starting point for the design implementation, as the design is an update to the PatternFly About Modal: http://www.patternfly.org/pattern-library/communication/about-modal/#/code/html-css.

**Comment by mindreeper2420** [comment]
@SMahil here is the background image that you should use for the modal:
![osiomodalbackground](https://cloud.githubusercontent.com/assets/4032718/25294842/052c25f4-26af-11e7-84d4-d8b6bbe4d282.png)

Just overlay the corporate logo onto the lower right corner, over the red.
