### ISSUE TITLE
fabric8-ui using hardcoded sso realms when obtaining github/oso tokens

### ISSUE THREAD

**Issue by alexeykazakov** [fabric8io/fabric8-ui#896]
I see calls to https://sso.prod-preview.openshift.io/auth/realms/fabric8/broker/openshift-v3/token and https://sso.prod-preview.openshift.io/auth/realms/fabric8/broker/github/token
when running fabirc8-ui and api locally.
But local api is using fabric8-test. Not fabric8.
So the correct URLs would be
https://sso.prod-preview.openshift.io/auth/realms/fabric8-test/broker/openshift-v3/token
and
https://sso.prod-preview.openshift.io/auth/realms/fabric8-test/broker/github/token
if running against local api (set by FABRIC8_WIT_API_URL="http://localhost:8080/api/")
This cause UI ignore already linked github and OSO when trying to login. Which prevents proper login.

cc: @xcoulon

**Comment by alexeykazakov** [comment]
Is there any env var which can be set to point fabric8-ui to proper realm?

**Comment by maxandersen** [comment]
I found this https://github.com/fabric8-ui/ngx-login-client/blob/master/src/app/auth/authentication.service.ts#L136

Here realm/fabric8 is hardcoded this should be made configurable and overridable when run/packaged.

**Comment by corinnekrych** [comment]
when I tried to hard-code it to `realm/fabric8-test` being in local env, I still got failure. there is 2 calls to KC:
https://sso.prod-preview.openshift.io/auth/realms/fabric8-test/broker/openshift-v3/token => 200
https://sso.prod-preview.openshift.io/auth/realms/fabric8-test/broker/github/token => 400

**Comment by maxandersen** [comment]
> {"errorMessage":"User [338feff0-e9c0-47f0-8276-f565ef444c6b] is not associated with identity provider [github]."}

@corinnekrych might just be bug that exist in both prod and test where it does not handle unlinked accounts.

What happens if you go to https://sso.prod-preview.openshift.io/auth/realms/fabric8-test/account/identity and do linking explicitly for your account ?

**Comment by corinnekrych** [comment]
I can't add gh it complains: Federated identity returned by github is already linked to another user.
![unspecified-1](https://cloud.githubusercontent.com/assets/1395710/25223526/e6d765d0-25bb-11e7-9971-8dd204558d58.png)

**Comment by corinnekrych** [comment]
@maxandersen But then if I go to http://localhost:3000/_home I am logged in...
![unspecified-2](https://cloud.githubusercontent.com/assets/1395710/25223651/417a5d44-25bc-11e7-804b-390f06176a55.png)

**Comment by maxandersen** [comment]
Good - at least gets us halfway.

Any chance you have another user with same github id registered?

**Comment by xcoulon** [comment]
I confirm that it works for me after changing the realm as suggested above (directly in `.js` file in the `/node_modules` directory of the project to make things more straightforward in my case).

**Comment by corinnekrych** [comment]
Indeed I had 2 users created and I was trying to link them to the same gh account.

**Comment by joshuawilson** [comment]
Just in case you still have 2 accounts pointing to your github account, you must unlink one of them.

**Comment by joshuawilson** [comment]
As a work around, you can go into the main UI and edit the node_modules of the file at https://github.com/fabric8-ui/ngx-login-client/blob/master/src/app/auth/authentication.service.ts#L147
