### ISSUE TITLE
Slashes/spaces shouldn't be part of area names 

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-ui#916]
Slashes/spaces shouldn't be part of area names 
![bug5](https://cloud.githubusercontent.com/assets/19172870/25219935/c5e91fc8-25cd-11e7-950f-6728054c8f7f.png)

**Comment by joshuawilson** [comment]
The slash is to show the parent. Though we should filter out any slash or space in the name it's self.

**Comment by joshuawilson** [comment]
Not a bug, works as designed.
