### ISSUE TITLE
"Create space" widget contains "Lorem ipsum" text

### ISSUE THREAD

**Issue by luebken** [fabric8io/fabric8-ui#918]
![screen shot 2017-04-20 at 11 23 07](https://cloud.githubusercontent.com/assets/53055/25223553/f624078c-25bb-11e7-8b24-05d11322ad10.png)

**Comment by luebken** [comment]
It differs for development process:

- Agile: "Lorem ipsum"
- Scrum: "Scrum is Scrum"
- Issue Tracking: "How boring"
- Scenario Driven: "We love Todd"

**Comment by joshuawilson** [comment]
@catrobson can you please provide text for each of these?
@mitchharpur can you please remove the text until you get the designs?

**Comment by joshuawilson** [comment]
@mitchharpur I'm going to take this one as we now have an API for it.

**Comment by joshuawilson** [comment]
Fixed
