### ISSUE TITLE
Create Space notification is hidden

### ISSUE THREAD

**Issue by luebken** [fabric8io/fabric8-ui#919]
When a new space is created the respective toast notification is hidden behind the widget / wizard for the next steps:

![screen shot 2017-04-20 at 11 29 01](https://cloud.githubusercontent.com/assets/53055/25223892/08bc1726-25bd-11e7-9a15-02f7376f238d.png)

Tested just now. On a Mac. Chrome: Version 57.0.2987.133

**Comment by joshuawilson** [comment]
@catrobson can you add this to your list of things to review please? Do we bring the notification forward? If so do we really need to button on the form that does the same thing? Do we not show a notification for this and just you the button on the form?

**Comment by mitchharpur** [comment]
appears to be fixed
