### ISSUE TITLE
Board view has odd spacing on card titles

### ISSUE THREAD

**Issue by qodfathr** [fabric8io/fabric8-ui#930]
It looks like it's using justified text; does not look good on this example:

![image](https://cloud.githubusercontent.com/assets/16322190/25237975/1de088ba-25ba-11e7-9e1c-c2ec0c7ae982.png)

**Comment by michaelkleinhenz** [comment]
@vikram-raj an you take a look?

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-planner#2022
