### ISSUE TITLE
Board view has invisibly sticky filtering

### ISSUE THREAD

**Issue by qodfathr** [fabric8io/fabric8-ui#931]
1. Go to board with many cards, only some assigned to you.
2. Filter to cards assigned to you
3. Go to another screen (e.g. click Create)
4. Return to Plan | Board

View is still filtered to only cards assigned to you, but there is no filter information at the top of the board.

I like the stickiness -- but the filter needs to be visible. Otherwise it looks like I lost nearly everything.

**Comment by michaelkleinhenz** [comment]
@vikram-raj can you look into this?

**Comment by michaelkleinhenz** [comment]
@sanbornsen maybe this is also an issue on the filters. Can you take a look?

**Comment by sanbornsen** [comment]
@michaelkleinhenz @qodfathr looks like the similar issue reported here - https://github.com/fabric8io/fabric8-planner/issues/1714

Try this - PR build - https://github.com/fabric8io/fabric8-planner/pull/1715

**Comment by sanbornsen** [comment]
Never mind, this is not fixed yet. This is a different issue than what I mentioned above. I am on it.

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-planner#2021
