### ISSUE TITLE
Workitems can be configured to have multiple parents

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-ui#945]
Enabling workitems to support multiple parents can worsen conditions where a workitem appears more than once in the UI:

![screenshot from 2017-04-20 14-47-24](https://cloud.githubusercontent.com/assets/642621/25247713/ab3573e6-25d9-11e7-8a04-5c5e0b86810f.png)

**Comment by joshuawilson** [comment]
Is this a tree list issue or a planner implementation of the tree list? @michaelkleinhenz @dlabrecq

**Comment by michaelkleinhenz** [comment]
All components are working as they were designed here. It is just that the combined function does not make sense. :-)
But we already have a solution in a PR. @baijum 
Also see the thread on devtools-planner on this. The solution will change the items displayed in the root level to only items that don't have a parent set.

**Comment by joshuawilson** [comment]
This issue was moved to fabric8io/fabric8-planner#2020
