### ISSUE TITLE
Space Name does not accept underscores

### ISSUE THREAD

**Issue by samuzzal-choudhury** [fabric8io/fabric8-ui#947]
**Test Environment**: https://openshift.io

While trying to create a space with a space name "sam_test_space", I got the following error -

> Name must contain only letters (upper case or lower case), numbers, spaces, underscores (_) or hyphens(-). It cannot start or end with a space, an underscore or a hyphen.

As per the above message my space name should have been a valid one. Replacing the underscores in the space names with hyphens made the error message disappear.

**Comment by corinnekrych** [comment]
@samuzzal-choudhury Fixed with https://github.com/fabric8-ui/ngx-fabric8-wit/pull/81
and new released ngx-fabric8-wit@v6.17.11
