### ISSUE TITLE
On creating a new project, the user must only use lowercase letters 

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-ui#949]
The error message displayed if uppercase letters are used refers only to "spaces and special characters."

--------------------------------
Before:
![screenshot from 2017-04-19 11-08-37](https://cloud.githubusercontent.com/assets/642621/25249177/fe898776-25de-11e7-9741-163d79a87268.png)

----------------------------------
After:
![screenshot from 2017-04-19 11-08-57](https://cloud.githubusercontent.com/assets/642621/25249176/fe849c2a-25de-11e7-8d66-72466629eac4.png)

**Comment by ldimaggi** [comment]
The issue here is that the user is not told that uppercase letters are considered as special characters.

**Comment by mitchharpur** [comment]
All text entered is automatically lowercased by a server side validation (there is a slight validation delay) ... the input is trimmed , spaces and underscores are replaced by dashes ... any remaining validation failures now have a clearer validation message
