### ISSUE TITLE
Validation for username is not working as expected

### ISSUE THREAD

**Issue by naina-verma** [fabric8io/fabric8-ui#958]
it says `Username must be less than 63 characters and can't begin with a dash or underscore. They may contain lowercase letters, numbers, dashes, or underscores.`

Actual behavior 
- While trying user-name with underscore/hyphens in between the characters not in beginning

Video link : https://drive.google.com/a/redhat.com/file/d/0B1qUq_laG6COaldTb2s4TDMwMGM/view?usp=sharing

**Comment by joshuawilson** [comment]
Closing as we have turned off the ability to edit the username.
