### ISSUE TITLE
Detail Add Type doesn't work correctly 

### ISSUE THREAD

**Issue by SMahil** [fabric8io/fabric8-ui#959]
Detail Add Type is not working correctly.
I have attached the video link to reproduce the error.

https://drive.google.com/open?id=0BzAb-YONh7fsZUc5ekhvbWFoeUE

**Comment by joshuawilson** [comment]
My browser doesn't support playing the video. Can you please list the steps to reproduce this?

**Comment by SMahil** [comment]
1. On space homepage click Work Item
2. detail page is broken. Its not overlaying the homepage

**Comment by joshuawilson** [comment]
and if you click the add work item and then scroll down you can still see the the Space dashboard (I had a smaller window due to having the dev console up)

**Comment by joshuawilson** [comment]
I think this is fixed.
