### ISSUE TITLE
User experiences 3-4 second delay in project name validation during "add to space"

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-ui#962]
Steps to recreate:

- Create a new user space - assign the space a name that includes an uppercase letter
- Click on 'add to space'
- Click on 'Select Technology stack and pipeline'
- The project name is automatically assigned the same name as the space - including the uppercase letter - this results in the next/finish buttons being set to disabled
- Remove the offending uppercase letter from the project name - and then click in or tab to another field in the project dialog
- At this point, the user experiences a 3-4 second delay before the next/finish buttons are enabled

**Comment by mitchharpur** [comment]
title bar Spinner buttons indicating validation is underway are now added on same page validations and page level for page transitions
