### ISSUE TITLE
User cannot 'add to space' in a space that contains an uppercase letter in its name

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-ui#963]
Steps to recreate:

* Create a new user space - assign the space a name that includes an uppercase letter
* Click on 'add to space'
* Click on 'Select Technology stack and pipeline'
* The project name is automatically assigned the same name as the space - including the uppercase letter - this results in the next/finish buttons being set to disabled
* Remove the offending uppercase letter from the project name - and then click in or tab to another field in the project dialog
* Click on Next
* After a 4-5 second delay, the uppercase letter is restored to the project name - the project is not created

Console log:
```

ForgeAppGenerator 5 Next request for command forge-quick-start :: begin :: 0.
main.a828878….bundle.js:1 Fabric8AppGeneratorService 5 AppGenerator executing the 'forge-quick-start :: begin :: 0' command ...
main.a828878….bundle.js:1 Object
main.a828878….bundle.js:1 Fabric8ForgeService 2 Forge GET request  : https://forge.api.prod-preview.openshift.io/forge/commands/fabric8-new-project
main.a828878….bundle.js:1 Fabric8ForgeService 2 Forge GET response : https://forge.api.prod-preview.openshift.io/forge/commands/fabric8-new-project
main.a828878….bundle.js:1 Object
main.a828878….bundle.js:1 Fabric8AppGeneratorService 5 AppGenerator 'forge-quick-start :: begin :: 0' command completed
main.a828878….bundle.js:1 Object
main.a828878….bundle.js:1 ForgeAppGenerator 5 Next response for command forge-quick-start :: begin :: 0.
main.a828878….bundle.js:1 Object
main.a828878….bundle.js:1 ForgeAppGenerator 5 Stored fieldset[4] into fieldset history
                  ... there are 2 responses in history ...
```

From this: 
![screenshot from 2017-04-21 08-41-37](https://cloud.githubusercontent.com/assets/642621/25277919/a126a57e-266e-11e7-9d55-a99a5ccb95b8.png)

To this:
![screenshot from 2017-04-21 08-42-01](https://cloud.githubusercontent.com/assets/642621/25277938/ad5bce50-266e-11e7-88de-22d66de0bd61.png)

**Comment by mitchharpur** [comment]
this is fixed. the space is now lowercased trimmed and  underscores are replaced with dashes and spaces replaced with dashed
