### ISSUE TITLE
After logging in on prod-preview.openshift.io, user's home page is stuck at a developer survey

### ISSUE THREAD

**Issue by ldimaggi** [fabric8io/fabric8-ui#983]
The user is able to navigate to other pages (such as 'view all spaces'), but the user's home page is always the survey:

![screenshot from 2017-04-22 08-48-27](https://cloud.githubusercontent.com/assets/642621/25304647/a320773a-2739-11e7-9634-3b0d2b0681dd.png)

**Comment by dlabrecq** [comment]
Fixed by https://github.com/fabric8io/fabric8-ui/pull/987

**Comment by ldimaggi** [comment]
Not being seen now - closing
